"use client";

import { useEffect, useRef, useState } from "react";
import { Activity, ArrowRight, BookOpen, Check, CheckCheck, ChevronRight, CircleHelp, Clock3, Dices, Fingerprint, Flag, Globe2, HardDrive, KeyRound, Layers, LockKeyhole, Mail, Network, Radio, RotateCcw, Search, Server, Shield, ShieldCheck, Sparkles, Terminal, Trophy, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Switch } from "@/components/ui/switch";
import { Progress } from "@/components/ui/progress";
import { attacks, procedures, scenarios, stages, newGame, playTurn, availableIn, getLead, getSuggestion, type Game, type Turn } from "@/lib/game";

const icons = [HardDrive, KeyRound, Network, Shield, Mail, Server, Layers, Globe2, Search, Fingerprint, Radio];
const stageIcons = [KeyRound, Network, RotateCcw, Radio];

export default function Home() {
  const [game, setGame] = useState<Game | null>(null);
  const [guided, setGuided] = useState(true);
  const [selected, setSelected] = useState<string | null>(null);
  const [rolling, setRolling] = useState(false);
  const [die, setDie] = useState(20);
  const [report, setReport] = useState<Turn | null>(null);
  const [rules, setRules] = useState(false);
  const [newConfirm, setNewConfirm] = useState(false);
  const [question, setQuestion] = useState<string | null>(null);
  const [debrief, setDebrief] = useState(false);
  const [scenarioChoice, setScenarioChoice] = useState(0);
  const stateRef = useRef(game);
  const busyRef = useRef(false);
  const timers = useRef<ReturnType<typeof setTimeout>[]>([]);
  stateRef.current = game;
  const activeScenario = scenarios[game?.scenario ?? scenarioChoice];
  const ScenarioIcon = activeScenario.icon;
  const proc = procedures.find(p => p.id === selected);
  const complete = game && game.status !== "playing";

  function start(index = scenarioChoice) {
    if (busyRef.current) return;
    setGame(newGame(index)); setSelected(null); setReport(null); setQuestion(null); setDebrief(false); setNewConfirm(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  }
  function run(id: string) {
    const current = stateRef.current;
    if (!current || busyRef.current || current.status !== "playing" || availableIn(current, id) > 0) return;
    busyRef.current = true; setRolling(true); setSelected(null);
    const interval = setInterval(() => setDie(1 + Math.floor(Math.random() * 20)), 80);
    const timeout = setTimeout(() => {
      clearInterval(interval);
      const next = playTurn(current, id);
      const result = next.turns[next.turns.length - 1];
      setDie(result.raw); setGame(next); setReport(result); setRolling(false); busyRef.current = false;
    }, 850);
    timers.current.push(interval, timeout);
  }
  useEffect(() => () => timers.current.forEach(clearTimeout), []);
  useEffect(() => {
    const context = (document as Document & {modelContext?: {registerTool: (tool: unknown, options: {signal: AbortSignal}) => void | Promise<void>}}).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    try {
      const registration = context.registerTool({
        name: "read_incident_state", title: "Read incident state",
        description: "Read the visible incident, discovered evidence, turn count and available procedures. Hidden attacks are not disclosed.",
        inputSchema: {type: "object", properties: {}, additionalProperties: false},
        annotations: {readOnlyHint: true, untrustedContentHint: false},
        execute(input: unknown) {
          if (!input || typeof input !== "object" || Array.isArray(input) || Object.keys(input).length) throw new Error("Expected an empty object.");
          const g = stateRef.current;
          if (!g) return {status: "briefing"};
          return {status:g.status,incident:scenarios[g.scenario].title,turnsUsed:g.turns.length,turnsRemaining:10-g.turns.length,
            discovered:g.revealed.map(id=>attacks.find(a=>a.id===id)?.title),lead:getLead(g),
            procedures:procedures.map(p=>({id:p.id,title:p.title,established:g.established.includes(p.id),cooldown:availableIn(g,p.id)}))};
        }
      }, {signal:lifecycle.signal});
      Promise.resolve(registration).catch(()=>{});
    } catch { /* Optional browser capability. */ }
    return () => lifecycle.abort();
  }, []);
  function dismissReport() {setReport(null);if(complete)setDebrief(true);}

  return <div className="app-shell">
    <header className="topbar">
      <a href="/" className="brand" aria-label="Breach Command home"><span className="brand-mark"><Shield size={24}/></span><span>BREACH<span className="brand-light">COMMAND</span></span></a>
      <div className="top-actions"><span className="solo-label"><Terminal size={14}/> SINGLE PLAYER</span><button className="quiet-button" onClick={()=>setRules(true)}><BookOpen size={17}/><span>Field guide</span></button>{game&&<button className="quiet-button" disabled={rolling} onClick={()=>setNewConfirm(true)} aria-label="New incident"><RotateCcw size={16}/><span>New incident</span></button>}</div>
    </header>
    {!game?<main className="briefing-screen">
      <div className="briefing-main"><div className="eyebrow"><span className="status-beacon"/> INCIDENT RESPONSE SIMULATION</div><h1>Find the breach.<br/><span>Follow the evidence.</span></h1><p className="intro">You lead the investigation. The computer holds the attack chain. Uncover all four stages in ten turns.</p><div className="briefing-chain" aria-label="Four attack stages">{stages.map((s,i)=>{const Icon=stageIcons[i];return <div key={s.name} style={{"--stage-color":s.color} as React.CSSProperties}><Icon size={22}/><span>{s.short}</span><small>0{i+1}</small></div>})}</div><div className="first-move"><Dices size={20}/><p>Choose a procedure. Roll the d20. Connect the evidence.</p></div></div>
      <section className="mission-panel"><div className="panel-top"><span className="eyebrow">YOUR NEXT ASSIGNMENT</span><span className="mono muted">0{scenarioChoice+1} / 06</span></div><div className="mission-symbol"><ScenarioIcon size={33} strokeWidth={1.4}/><span>{activeScenario.sector}</span></div><h2>{activeScenario.title}</h2><p>{activeScenario.summary}</p><div className="mission-selector" aria-label="Select incident">{scenarios.map((s,i)=><button key={s.id} aria-label={s.title} aria-pressed={scenarioChoice===i} className={scenarioChoice===i?"active":""} onClick={()=>setScenarioChoice(i)}>{String(i+1).padStart(2,"0")}</button>)}</div><div className="guided-control"><div><label htmlFor="guided-start">Guided investigation</label><small>Captain recommendations. Same dice, same rules.</small></div><Switch id="guided-start" checked={guided} onCheckedChange={setGuided}/></div><button className="primary-button start-button" onClick={()=>start()}>Begin investigation <ArrowRight size={19}/></button><div className="mission-meta"><span><Clock3 size={14}/> 10–20 minutes solo</span><span><LockKeyhole size={14}/> No real systems</span></div></section>
      <p className="adaptation-note">An unofficial solo adaptation of <a href="https://www.blackhillsinfosec.com/tools/backdoorsandbreaches/" target="_blank" rel="noreferrer">Backdoors &amp; Breaches</a>. Original scenarios and card text. Rule-based computer captain, not a live AI service.</p>
    </main>:<main className="game-screen">
      <section className="game-heading"><div><div className="eyebrow">CASE 0{game.scenario+1} <span className="separator">/</span> {activeScenario.sector}</div><h1>{activeScenario.title}</h1></div><div className="turn-meter"><span className="mono">{complete?"FINAL STATUS":"INVESTIGATION WINDOW"}</span><div>{complete?(game.status==="won"?"Chain uncovered":game.status==="exercise"?"Exercise concluded":"Window closed"):<><strong>{10-game.turns.length}</strong> turns remaining</>}</div><Progress value={(10-game.turns.length)*10} className="turn-progress" aria-label="Turns remaining"/></div></section>
      <div className="game-layout"><div className="table-area">
        <section className="attack-section"><div className="section-heading"><h2>Attack chain</h2><span className="mono muted">{game.revealed.length} / 4 REVEALED</span></div><div className="attack-grid">{stages.map((stage,i)=>{const a=attacks.find(a=>a.id===game.chain[i])!;const revealed=game.revealed.includes(a.id);const Icon=stageIcons[i];return <div className={`attack-card ${revealed?"revealed":"concealed"}`} key={stage.name} style={{"--stage-color":stage.color} as React.CSSProperties}><div className="attack-card-top"><span className="mono">0{i+1}</span>{revealed?<Check size={16}/>:<LockKeyhole size={14}/>}</div><div className="attack-emblem"><Icon size={28} strokeWidth={1.3}/></div><small>{stage.name}</small><h3>{revealed?a.title:"Unknown technique"}</h3><span className="attack-footer">{revealed?"EVIDENCE CONFIRMED":"AWAITING EVIDENCE"}</span></div>})}</div></section>
        {complete?<section className="end-banner"><div className="end-icon">{game.status==="won"?<Trophy/>:<Flag/>}</div><div><h2>{game.status==="won"?"You connected the evidence.":game.status==="exercise"?"This was an authorised exercise.":"The investigation window has closed."}</h2><p>{game.status==="won"?`All four stages revealed in ${game.turns.length} turns. Review what worked and what to improve.`:"The captain has unsealed the case. Review the complete attack chain and your decisions."}</p></div><button className="primary-button" onClick={()=>setDebrief(true)}>View debrief <ArrowRight size={17}/></button></section>:<section className="lead-strip"><Activity size={20}/><div><span className="eyebrow">CURRENT LEAD</span><p>{getLead(game)}</p></div></section>}
        <section className="procedure-section"><div className="section-heading"><div><h2>Response procedures</h2><p>Choose one action per turn. Every action has a three-turn cooldown.</p></div><span className="established-key">+3 Established</span></div>{guided&&!complete&&<div className="guide-nudge"><Sparkles size={15}/><span>Captain recommends <strong>{getSuggestion(game)?.title??"reviewing the evidence"}</strong>. Match your next action to the lead.</span></div>}<div className="procedure-grid">{procedures.map((p,i)=>{const Icon=icons[i];const cooldown=availableIn(game,p.id);const established=game.established.includes(p.id);return <button key={p.id} data-procedure={p.id} className={`procedure-card ${established?"established":""} ${cooldown?"cooling":""}`} disabled={rolling||!!complete||cooldown>0} onClick={()=>setSelected(p.id)} aria-label={`${p.title}${established?", established, plus 3":""}${cooldown?`, available in ${cooldown} turns`:""}`}><div className="procedure-top"><span className="procedure-icon"><Icon size={20}/></span><span className={`procedure-badge ${established?"bonus":""}`}>{cooldown?<><Clock3 size={12}/> {cooldown} turn{cooldown===1?"":"s"}</>:established?"+3":"+0"}</span></div><h3>{p.title}</h3><p>{p.short}</p><div className="procedure-bottom"><span>{cooldown?"ON COOLDOWN":established?"ESTABLISHED":"STANDARD"}</span>{!cooldown&&<ChevronRight size={15}/>}</div></button>})}</div></section>
      </div><aside className="captain-column">
        <section className="captain-panel"><div className="captain-label"><span className="captain-avatar"><Terminal size={23}/></span><div><h2>Incident Captain</h2><span>COMPUTER FACILITATOR</span></div></div><div className="brief-label">INITIAL BRIEFING</div><p className="captain-brief">{activeScenario.brief}</p><div className="captain-divider"/><div className="brief-label">ASK YOUR CAPTAIN <span>Free action</span></div><div className="question-list">{[{id:"scope",label:"What is in scope?"},{id:"timeline",label:"What do we know so far?"},{id:"constraints",label:"What are our constraints?"}].map(q=><button key={q.id} className={question===q.id?"active":""} onClick={()=>setQuestion(question===q.id?null:q.id)}>{q.label}<ChevronRight size={14}/></button>)}</div>{question&&<div className="captain-answer" aria-live="polite">{question==="scope"?activeScenario.scope:question==="constraints"?activeScenario.constraints:`${activeScenario.timeline} ${getLead(game)}`}</div>}<div className="guided-inline"><label htmlFor="guided-game"><Sparkles size={14}/> Guided mode</label><Switch id="guided-game" checked={guided} onCheckedChange={setGuided}/></div></section>
        <section className="journal-panel"><div className="section-heading"><h2>Incident log</h2><span className="mono muted">{String(game.turns.length).padStart(2,"0")}</span></div>{!game.turns.length?<div className="empty-log"><Terminal size={21}/><p>Investigation opened.</p><small>Your findings will appear here. Select a procedure to make your first move.</small></div>:<div className="journal-entries">{[...game.turns].reverse().map(t=><button className="log-entry" key={t.number} onClick={()=>setReport(t)}><span className={`log-number ${t.revealed?"found":t.success?"passed":"failed"}`}>{String(t.number).padStart(2,"0")}</span><div><strong>{procedures.find(p=>p.id===t.procedure)?.title}</strong><span>{t.revealed?"Attack stage revealed":t.success?"No new evidence":"Action unsuccessful"}{t.inject?" · Inject":""}</span></div><span className="roll-total">{t.total}</span></button>)}</div>}</section><div className="rules-reminder"><Dices size={18}/><p>11+ succeeds. Natural 1, natural 20 or three failed rolls trigger an inject.</p></div>
      </aside></div><footer className="game-footer"><span>BREACH COMMAND <span className="separator">/</span> SINGLE-PLAYER TABLETOP</span><button onClick={()=>setRules(true)}>Rules &amp; attribution <CircleHelp size={14}/></button></footer>
    </main>}

    <Dialog open={!!proc&&!rolling} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="game-dialog"><DialogHeader><div className="eyebrow">PREPARE RESPONSE</div><DialogTitle>{proc?.title}</DialogTitle><DialogDescription>{proc?.description}</DialogDescription></DialogHeader>{proc&&game&&<><div className="action-note"><span className="eyebrow">INVESTIGATION QUESTION</span><p>{proc.question}</p></div><div className="roll-preview"><div><span>D20</span><small>Dice roll</small></div><span>+</span><div><span>{game.established.includes(proc.id)?3:0}{game.nextModifier!==0?` ${game.nextModifier>0?"+":""}${game.nextModifier}`:""}</span><small>Modifier{game.nextModifier!==0?" (inject included)":""}</small></div><span>≥</span><div><span>11</span><small>To succeed</small></div></div><p className="muted small">Success only reveals a stage if this procedure matches an undiscovered attack. This action consumes one turn.</p><button className="primary-button full" onClick={()=>run(proc.id)}><Dices size={19}/> Run procedure</button></>}</DialogContent></Dialog>
    <Dialog open={rolling} onOpenChange={()=>{}}><DialogContent className="roll-dialog" showCloseButton={false} onEscapeKeyDown={e=>e.preventDefault()} onPointerDownOutside={e=>e.preventDefault()}><DialogHeader><DialogTitle>Running procedure</DialogTitle><DialogDescription>The Incident Captain is resolving your action.</DialogDescription></DialogHeader><div className="die rolling"><Dices size={32}/><strong>{die}</strong><span>D20</span></div></DialogContent></Dialog>
    <Dialog open={!!report} onOpenChange={open=>{if(!open)dismissReport()}}><DialogContent className="game-dialog report-dialog"><DialogHeader><div className="eyebrow">CAPTAIN’S REPORT <span className="separator">/</span> TURN {report?.number}</div><DialogTitle>{report?.revealed?"Evidence confirmed.":report?.success?"No new attack identified.":"The action was unsuccessful."}</DialogTitle><DialogDescription>{report&&procedures.find(p=>p.id===report.procedure)?.title}</DialogDescription></DialogHeader>{report&&<><div className={`result-roll ${report.success?"success":"failure"}`}><span className="result-die">{report.raw}</span><div><span>Natural roll {report.raw} {report.modifier>=0?"+":"−"} {Math.abs(report.modifier)} modifier</span><strong>{report.total} <span>/ {report.success?"Success":"Failure"}</span></strong></div>{report.success?<CheckCheck size={23}/>:<X size={23}/>}</div><p>{report.narrative}</p>{report.revealed&&<div className="discovery"><ShieldCheck size={22}/><div><span>{stages[attacks.find(a=>a.id===report.revealed)!.stage].name}</span><strong>{attacks.find(a=>a.id===report.revealed)?.title}</strong></div></div>}{report.inject&&<div className="inject-box"><span className="eyebrow">INJECT <span className="separator">/</span> {report.inject.reason}</span><h3>{report.inject.title}</h3><p>{report.inject.text}</p><strong>{report.inject.effectLabel}</strong></div>}<p className="small muted">Every procedure normally cools down for three turns; a restoration inject may override this. {report.success&&!report.revealed?"A passed roll is not proof that a technique is absent.":""}</p><button className="primary-button full" onClick={dismissReport}>{complete?"Open debrief":"Continue investigation"}<ArrowRight size={17}/></button></>}</DialogContent></Dialog>
    <Dialog open={rules} onOpenChange={setRules}><DialogContent className="game-dialog wide-dialog"><DialogHeader><div className="eyebrow">FIELD GUIDE</div><DialogTitle>One incident. Four hidden stages.</DialogTitle><DialogDescription>Classic cooperative mechanics, adapted for solo play.</DialogDescription></DialogHeader><div className="rules-content"><div className="rules-grid">
      <section><h3>01 / Your objective</h3><p>Reveal four attack stages within ten turns. You choose the response; the computer manages the hidden case. Discovery is the win condition, not proof of containment.</p></section>
      <section><h3>02 / Procedures &amp; dice</h3><p>Play one available procedure per turn. Roll a fair d20: a total of 11 or more succeeds. Four randomly established procedures add +3. Other procedures add +0. Injects may modify the next roll.</p></section>
      <section><h3>03 / Match the evidence</h3><p>Success reveals one matching hidden stage. If several match, the computer chooses the earliest undiscovered stage. If none match, no technique is revealed. Stages need not be found in order.</p></section>
      <section><h3>04 / Cooldowns</h3><p>Every played procedure is unavailable for three intervening turns, regardless of outcome. Used on turn 1, it returns on turn 5. Captain questions are free actions.</p></section>
      <section><h3>05 / Unexpected events</h3><p>A natural 1 or 20, or three consecutive failed rolls, draws an inject. Only the raw die face triggers natural-roll events. Resolve the procedure first. Original injects can modify the next roll, restore a procedure, reveal evidence or end an authorised exercise.</p></section>
      <section><h3>06 / Solo conventions</h3><p>Overlapping triggers draw only one inject. Any passed roll resets the failure streak; three failures draw an inject and reset it. The tenth action and its inject resolve before the result. Four discoveries take precedence over an exercise-ending inject.</p></section>
    </div><section className="attribution"><h3>About this adaptation</h3><p>Inspired by Backdoors &amp; Breaches, created by Black Hills Information Security and Active Countermeasures, with the classic guide published by BHIS and Antisyphon Training. This unofficial adaptation is not affiliated with or endorsed by the creators. It uses original card wording, six fictional settings and a rule-based computer captain. The full commercial deck, official artwork and expansion Consultants are not included. Guided mode recommends actions without changing the dice or rules. Sessions reset on page refresh.</p><a href="https://www.blackhillsinfosec.com/wp-content/uploads/2024/03/BnB_VisualGuide_v2_03052024.pdf" target="_blank" rel="noreferrer">Read the official classic rules <ArrowRight size={14}/></a></section></div></DialogContent></Dialog>
    <Dialog open={debrief} onOpenChange={setDebrief}><DialogContent className="game-dialog wide-dialog"><DialogHeader><div className="eyebrow">AFTER-ACTION REVIEW</div><DialogTitle>{game?.status==="won"?"Attack chain uncovered.":game?.status==="exercise"?"Exercise concluded.":"There is more to uncover."}</DialogTitle><DialogDescription>{game?`${game.revealed.length} of 4 stages found in ${game.turns.length} turns. A learning outcome, not a security assessment.`:""}</DialogDescription></DialogHeader>{game&&<><div className="debrief-stats"><div><strong>{game.turns.filter(t=>t.success).length}/{game.turns.length}</strong><span>Rolls succeeded</span></div><div><strong>{game.turns.filter(t=>t.revealed).length}</strong><span>Procedure discoveries</span></div><div><strong>{game.turns.filter(t=>t.inject).length}</strong><span>Injects encountered</span></div></div><div className="debrief-chain">{game.chain.map((id,i)=>{const a=attacks.find(a=>a.id===id)!;return <section key={id} style={{"--stage-color":stages[i].color} as React.CSSProperties}><span className="eyebrow">0{i+1} / {stages[i].name}<span className={game.revealed.includes(id)?"found-label":"missed-label"}>{game.revealed.includes(id)?"FOUND":"UNRESOLVED"}</span></span><h3>{a.title}</h3><p>{a.evidence}</p><small>Detectable with: {a.detect.map(id=>procedures.find(p=>p.id===id)?.title).join(" · ")}</small></section>})}</div><section className="debrief-learning"><h3>Take this back to your team</h3><p>{game.turns.some(t=>t.success&&!t.revealed)?"Some actions passed without finding new evidence. Did each action test a specific hypothesis, or simply use an available tool?":"Does your team actually have the logs, permissions and practised runbooks assumed by these actions?"}</p><p>{activeScenario.lesson}</p><p>Next, discuss containment, evidence preservation and safe recovery. Finding the chain does not make the environment safe.</p></section><button className="primary-button full" onClick={()=>{setGame(null);setDebrief(false);setScenarioChoice((game.scenario+1)%scenarios.length)}}>Choose next incident <ArrowRight size={18}/></button></>}</DialogContent></Dialog>
    <AlertDialog open={newConfirm} onOpenChange={setNewConfirm}><AlertDialogContent className="game-dialog"><AlertDialogHeader><AlertDialogTitle>Leave this investigation?</AlertDialogTitle><AlertDialogDescription>Your current incident and turn history will be cleared. You can select a new case from the briefing screen.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep investigating</AlertDialogCancel><AlertDialogAction onClick={()=>{setGame(null);setNewConfirm(false);setQuestion(null);setReport(null);setSelected(null)}}>Choose a new incident</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
