"use client";

import { useEffect, useRef, useState } from "react";
import { Activity, ArrowRight, BookOpen, Check, CheckCheck, ChevronRight, CircleHelp, Clock3, Dices, Fingerprint, Flag, Globe2, HardDrive, KeyRound, Layers, LockKeyhole, Mail, Network, Radio, RotateCcw, Search, Server, Shield, ShieldCheck, Sparkles, Terminal, Trophy, X, Zap, Eye, Siren, HeartPulse } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Switch } from "@/components/ui/switch";
import { Progress } from "@/components/ui/progress";
import { attacks, procedures, scenarios, stages, difficulties, responseOptions, newGame, playTurn, resolveDecision, resolveResponse, availableIn, getLead, getCoachPrompt, getOutcome, type Difficulty, type Game, type Turn } from "@/lib/game";

const icons = [HardDrive, KeyRound, Network, Shield, Mail, Server, Layers, Globe2, Search, Fingerprint, Radio];
const stageIcons = [KeyRound, Network, RotateCcw, Radio];

export default function Home() {
  const [game,setGame]=useState<Game|null>(null);
  const [guided,setGuided]=useState(true);
  const [difficulty,setDifficulty]=useState<Difficulty>("operational");
  const [selected,setSelected]=useState<string|null>(null);
  const [rolling,setRolling]=useState(false);
  const [die,setDie]=useState(20);
  const [report,setReport]=useState<Turn|null>(null);
  const [rules,setRules]=useState(false);
  const [newConfirm,setNewConfirm]=useState(false);
  const [question,setQuestion]=useState<string|null>(null);
  const [debrief,setDebrief]=useState(false);
  const [scenarioChoice,setScenarioChoice]=useState(0);
  const stateRef=useRef(game); const busyRef=useRef(false); const timers=useRef<ReturnType<typeof setTimeout>[]>([]);
  stateRef.current=game;
  const activeScenario=scenarios[game?.scenario??scenarioChoice];
  const ScenarioIcon=activeScenario.icon;
  const proc=procedures.find(p=>p.id===selected);
  const ended=!!game&&["won","lost","exercise"].includes(game.status);
  const config=game?difficulties[game.difficulty]:difficulties[difficulty];

  function start(index=scenarioChoice){if(busyRef.current)return;setGame(newGame(index,difficulty));setSelected(null);setReport(null);setQuestion(null);setDebrief(false);setNewConfirm(false);window.scrollTo({top:0,behavior:"smooth"});}
  function run(id:string){const current=stateRef.current;if(!current||busyRef.current||current.status!=="playing"||current.pendingDecision||availableIn(current,id)>0)return;busyRef.current=true;setRolling(true);setSelected(null);const interval=setInterval(()=>setDie(1+Math.floor(Math.random()*20)),80);const timeout=setTimeout(()=>{clearInterval(interval);const next=playTurn(current,id);const result=next.turns.at(-1)!;setDie(result.raw);setGame(next);setReport(result);setRolling(false);busyRef.current=false;},850);timers.current.push(interval,timeout);}
  function decide(choice:"preserve"|"disrupt"){const current=stateRef.current;if(!current)return;setGame(resolveDecision(current,choice));}
  function respond(choice:string){const current=stateRef.current;if(!current)return;const next=resolveResponse(current,choice);setGame(next);if(next.status==="won")setDebrief(true);}
  function dismissReport(){if(game?.pendingDecision)return;setReport(null);if(ended)setDebrief(true);}

  useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
  useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{const registration=context.registerTool({name:"read_incident_state",title:"Read incident state",description:"Read the visible incident, impact, discovered evidence and available procedures. Hidden attacks are not disclosed.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).length)throw new Error("Expected an empty object.");const g=stateRef.current;if(!g)return{status:"briefing"};const c=difficulties[g.difficulty];return{status:g.status,difficulty:g.difficulty,incident:scenarios[g.scenario].title,turnsUsed:g.turns.length,turnsRemaining:Math.max(0,c.maxTurns-g.turns.length),impact:g.impact,discovered:g.revealed.map(id=>attacks.find(a=>a.id===id)?.title),lead:getLead(g),procedures:procedures.map(p=>({id:p.id,title:p.title,established:g.established.includes(p.id),cooldown:availableIn(g,p.id)}))};}}, {signal:lifecycle.signal});Promise.resolve(registration).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);

  const answer=game&&question==="scope"?activeScenario.scope:question==="constraints"?activeScenario.constraints:question==="impact"?activeScenario.impact:question==="known"?`${activeScenario.timeline} ${getLead(game!)}`:question==="assumptions"?"Treat alerts, valid credentials and successful procedures as evidence, not conclusions. The computer may select any technique compatible with this scenario.":"";

  return <div className="app-shell">
    <header className="topbar"><a href="/" className="brand" aria-label="Breach Command home"><span className="brand-mark"><Shield size={24}/></span><span>BREACH<span className="brand-light">COMMAND</span></span></a><div className="top-actions"><span className="solo-label"><Terminal size={14}/> SINGLE PLAYER</span><button className="quiet-button" onClick={()=>setRules(true)}><BookOpen size={17}/><span>Field guide</span></button>{game&&<button className="quiet-button" disabled={rolling} onClick={()=>setNewConfirm(true)} aria-label="New incident"><RotateCcw size={16}/><span>New incident</span></button>}</div></header>
    {!game?<main className="briefing-screen">
      <div className="briefing-main"><div className="eyebrow"><span className="status-beacon"/> INCIDENT RESPONSE SIMULATION</div><h1>Find the breach.<br/><span>Control the impact.</span></h1><p className="intro">You lead the investigation. The computer hides the attack chain, escalates business pressure and challenges your containment decisions.</p><div className="briefing-chain" aria-label="Four attack stages">{stages.map((s,i)=>{const Icon=stageIcons[i];return <div key={s.name} style={{"--stage-color":s.color} as React.CSSProperties}><Icon size={22}/><span>{s.short}</span><small>0{i+1}</small></div>})}</div><div className="first-move"><Dices size={20}/><p>Investigate, preserve or disrupt, then contain and recover.</p></div></div>
      <section className="mission-panel"><div className="panel-top"><span className="eyebrow">YOUR NEXT ASSIGNMENT</span><span className="mono muted">0{scenarioChoice+1} / 06</span></div><div className="mission-symbol"><ScenarioIcon size={33} strokeWidth={1.4}/><span>{activeScenario.sector}</span></div><h2>{activeScenario.title}</h2><p>{activeScenario.summary}</p><div className="mission-selector" aria-label="Select incident">{scenarios.map((s,i)=><button key={s.id} aria-label={s.title} aria-pressed={scenarioChoice===i} className={scenarioChoice===i?"active":""} onClick={()=>setScenarioChoice(i)}>{String(i+1).padStart(2,"0")}</button>)}</div><div className="difficulty-picker"><span className="eyebrow">DIFFICULTY</span><div>{(Object.keys(difficulties) as Difficulty[]).map(id=><button key={id} className={difficulty===id?"active":""} aria-pressed={difficulty===id} onClick={()=>setDifficulty(id)}><strong>{difficulties[id].title}</strong><small>{difficulties[id].maxTurns} turns · {difficulties[id].threshold}+</small></button>)}</div><p>{difficulties[difficulty].description}</p></div><div className="guided-control"><div><label htmlFor="guided-start">Guided reflection</label><small>Strategic prompts, never the correct card.</small></div><Switch id="guided-start" checked={guided} onCheckedChange={setGuided}/></div><button className="primary-button start-button" onClick={()=>start()}>Begin investigation <ArrowRight size={19}/></button><div className="mission-meta"><span><Clock3 size={14}/> 15–25 minutes solo</span><span><LockKeyhole size={14}/> No real systems</span></div></section>
      <p className="adaptation-note">An unofficial solo adaptation inspired by <a href="https://www.blackhillsinfosec.com/tools/backdoorsandbreaches/" target="_blank" rel="noreferrer">Backdoors &amp; Breaches</a>. Original scenarios and card text. Rule-based computer facilitator.</p>
    </main>:<main className="game-screen">
      <section className="game-heading"><div><div className="eyebrow">CASE 0{game.scenario+1} <span className="separator">/</span> {activeScenario.sector} <span className="separator">/</span> {config.title.toUpperCase()}</div><h1>{activeScenario.title}</h1></div><div className="case-meters"><div className="turn-meter"><span className="mono">{game.status==="response"?"RESPONSE PHASE":ended?"FINAL STATUS":"INVESTIGATION WINDOW"}</span><div>{!ended&&game.status!=="response"?<><strong>{Math.max(0,config.maxTurns-game.turns.length)}</strong> turns remaining</>:game.status==="response"?"Contain and recover":game.status==="won"?"Response complete":game.status==="exercise"?"Exercise concluded":"Window closed"}</div><Progress value={Math.max(0,(config.maxTurns-game.turns.length)/config.maxTurns*100)} className="turn-progress" aria-label="Turns remaining"/></div><div className={`impact-meter ${game.impact>=70?"critical":""}`}><span className="mono">BUSINESS IMPACT</span><strong>{game.impact}</strong><Progress value={game.impact} aria-label="Business impact"/><small>{game.impact<40?"Contained":game.impact<70?"Rising":"Critical"}</small></div></div></section>
      <div className="game-layout"><div className="table-area">
        <section className="attack-section"><div className="section-heading"><h2>Attack chain</h2><span className="mono muted">{game.revealed.length} / 4 REVEALED</span></div><div className="attack-grid">{stages.map((stage,i)=>{const a=attacks.find(a=>a.id===game.chain[i])!;const revealed=game.revealed.includes(a.id);const Icon=stageIcons[i];return <div className={`attack-card ${revealed?"revealed":"concealed"}`} key={stage.name} style={{"--stage-color":stage.color} as React.CSSProperties}><div className="attack-card-top"><span className="mono">0{i+1}</span>{revealed?<Check size={16}/>:<LockKeyhole size={14}/>}</div><div className="attack-emblem"><Icon size={28} strokeWidth={1.3}/></div><small>{stage.name}</small><h3>{revealed?a.title:"Unknown technique"}</h3><span className="attack-footer">{revealed?"EVIDENCE CONFIRMED":"AWAITING EVIDENCE"}</span></div>})}</div></section>
        {ended?<section className="end-banner"><div className="end-icon">{game.status==="won"?<Trophy/>:<Flag/>}</div><div><h2>{game.status==="won"?getOutcome(game).title:game.status==="exercise"?"This was an authorised exercise.":"The incident outran the response."}</h2><p>{game.status==="won"?`Outcome ${getOutcome(game).grade}. Review how investigation and response choices shaped the result.`:"The captain has unsealed the case. Review the evidence and decisions."}</p></div><button className="primary-button" onClick={()=>setDebrief(true)}>View debrief <ArrowRight size={17}/></button></section>:game.status==="response"?<ResponsePanel game={game} onChoose={respond}/>:<section className="lead-strip"><Activity size={20}/><div><span className="eyebrow">CURRENT INTELLIGENCE</span><p>{getLead(game)}</p></div></section>}
        {game.status==="playing"&&<section className="procedure-section"><div className="section-heading"><div><h2>Investigation procedures</h2><p>Choose one action per turn. Used actions cool down for three turns.</p></div><span className="established-key">+3 Established</span></div>{guided&&<div className="guide-nudge"><Sparkles size={15}/><span><strong>Captain’s prompt:</strong> {getCoachPrompt(game)}</span></div>}<div className="procedure-grid">{procedures.map((p,i)=>{const Icon=icons[i];const cooldown=availableIn(game,p.id);const established=game.established.includes(p.id);return <button key={p.id} data-procedure={p.id} className={`procedure-card ${established?"established":""} ${cooldown?"cooling":""}`} disabled={rolling||cooldown>0||!!game.pendingDecision} onClick={()=>setSelected(p.id)} aria-label={`${p.title}${established?", established, plus 3":""}${cooldown?`, available in ${cooldown} turns`:""}`}><div className="procedure-top"><span className="procedure-icon"><Icon size={20}/></span><span className={`procedure-badge ${established?"bonus":""}`}>{cooldown?<><Clock3 size={12}/> {cooldown} turn{cooldown===1?"":"s"}</>:established?"+3":"+0"}</span></div><h3>{p.title}</h3><p>{p.short}</p><div className="procedure-bottom"><span>{cooldown?"ON COOLDOWN":established?"ESTABLISHED":"STANDARD"}</span>{!cooldown&&<ChevronRight size={15}/>}</div></button>})}</div></section>}
      </div><aside className="captain-column">
        <section className="captain-panel"><div className="captain-label"><span className="captain-avatar"><Terminal size={23}/></span><div><h2>Incident Captain</h2><span>COMPUTER FACILITATOR</span></div></div><div className="brief-label">SITUATION</div><p className="captain-brief">{activeScenario.brief}</p><div className="captain-divider"/><div className="brief-label">ASK YOUR CAPTAIN <span>Free action</span></div><div className="question-list">{[{id:"scope",label:"What is in scope?"},{id:"known",label:"What is confirmed?"},{id:"impact",label:"What is at risk?"},{id:"constraints",label:"What limits us?"},{id:"assumptions",label:"What should we challenge?"}].map(q=><button key={q.id} className={question===q.id?"active":""} onClick={()=>setQuestion(question===q.id?null:q.id)}>{q.label}<ChevronRight size={14}/></button>)}</div>{question&&<div className="captain-answer" aria-live="polite">{answer}</div>}<div className="guided-inline"><label htmlFor="guided-game"><Sparkles size={14}/> Guided reflection</label><Switch id="guided-game" checked={guided} onCheckedChange={setGuided}/></div></section>
        <section className="journal-panel"><div className="section-heading"><h2>Incident log</h2><span className="mono muted">{String(game.turns.length).padStart(2,"0")}</span></div>{!game.turns.length?<div className="empty-log"><Terminal size={21}/><p>Investigation opened.</p><small>Findings, pressure and decisions will appear here.</small></div>:<div className="journal-entries">{[...game.turns].reverse().map(t=><button className="log-entry" key={t.number} onClick={()=>setReport(t)}><span className={`log-number ${t.revealed?"found":t.success?"passed":"failed"}`}>{String(t.number).padStart(2,"0")}</span><div><strong>{procedures.find(p=>p.id===t.procedure)?.title}</strong><span>{t.revealed?"Stage revealed":t.success?"No new evidence":"Action unsuccessful"} · Impact {t.impactChange>=0?"+":""}{t.impactChange}</span></div><span className="roll-total">{t.total}</span></button>)}</div>}</section><div className="rules-reminder"><Dices size={18}/><p>{config.threshold}+ succeeds. Natural 1, natural 20 or three failed rolls trigger an inject.</p></div>
      </aside></div><footer className="game-footer"><span>BREACH COMMAND <span className="separator">/</span> SINGLE-PLAYER TABLETOP</span><button onClick={()=>setRules(true)}>Rules &amp; attribution <CircleHelp size={14}/></button></footer>
    </main>}

    <Dialog open={!!proc&&!rolling} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="game-dialog"><DialogHeader><div className="eyebrow">PREPARE ACTION</div><DialogTitle>{proc?.title}</DialogTitle><DialogDescription>{proc?.description}</DialogDescription></DialogHeader>{proc&&game&&<><div className="action-note"><span className="eyebrow">HYPOTHESIS CHECK</span><p>{proc.question}</p></div><div className="roll-preview"><div><span>D20</span><small>Dice roll</small></div><span>+</span><div><span>{game.established.includes(proc.id)?3:0}{game.nextModifier!==0?` ${game.nextModifier>0?"+":""}${game.nextModifier}`:""}</span><small>Modifier</small></div><span>≥</span><div><span>{config.threshold}</span><small>To succeed</small></div></div><p className="muted small">Success reveals a stage only when this evidence source matches an undiscovered technique. The action consumes one turn and may increase impact.</p><button className="primary-button full" onClick={()=>run(proc.id)}><Dices size={19}/> Run procedure</button></>}</DialogContent></Dialog>
    <Dialog open={rolling} onOpenChange={()=>{}}><DialogContent className="roll-dialog" showCloseButton={false} onEscapeKeyDown={e=>e.preventDefault()} onPointerDownOutside={e=>e.preventDefault()}><DialogHeader><DialogTitle>Running procedure</DialogTitle><DialogDescription>The Incident Captain is resolving evidence and pressure.</DialogDescription></DialogHeader><div className="die rolling"><Dices size={32}/><strong>{die}</strong><span>D20</span></div></DialogContent></Dialog>
    <Dialog open={!!report} onOpenChange={open=>{if(!open)dismissReport()}}><DialogContent className="game-dialog report-dialog"><DialogHeader><div className="eyebrow">CAPTAIN’S REPORT <span className="separator">/</span> TURN {report?.number}</div><DialogTitle>{report?.revealed?"Evidence confirmed.":report?.success?"No new attack identified.":"The action was unsuccessful."}</DialogTitle><DialogDescription>{report&&procedures.find(p=>p.id===report.procedure)?.title}</DialogDescription></DialogHeader>{report&&game&&<><div className={`result-roll ${report.success?"success":"failure"}`}><span className="result-die">{report.raw}</span><div><span>Natural roll {report.raw} {report.modifier>=0?"+":"−"} {Math.abs(report.modifier)} modifier</span><strong>{report.total} <span>/ {report.success?"Success":"Failure"}</span></strong></div>{report.success?<CheckCheck size={23}/>:<X size={23}/>}</div><p>{report.narrative}</p>{report.revealed&&<div className="discovery"><ShieldCheck size={22}/><div><span>{stages[attacks.find(a=>a.id===report.revealed)!.stage].name}</span><strong>{attacks.find(a=>a.id===report.revealed)?.title}</strong></div></div>}{report.inject&&<div className="inject-box"><span className="eyebrow">INJECT <span className="separator">/</span> {report.inject.reason}</span><h3>{report.inject.title}</h3><p>{report.inject.text}</p><strong>{report.inject.effectLabel}</strong></div>}{game.pendingDecision&&<div className="evidence-decision"><span className="eyebrow">OPERATIONAL DECISION REQUIRED</span><h3>What do you do with the confirmed evidence?</h3><div><button onClick={()=>decide("preserve")}><Eye size={20}/><strong>Preserve and observe</strong><span>Better next investigation: +2 roll<br/>Attacker gains time: impact +8</span></button><button onClick={()=>decide("disrupt")}><Siren size={20}/><strong>Disrupt immediately</strong><span>Reduce impact by 12<br/>Lose telemetry: next roll −1</span></button></div></div>}<p className="small muted">Business impact changed by {report.impactChange>=0?"+":""}{report.impactChange}. A passed roll is not proof that a technique is absent.</p>{!game.pendingDecision&&<button className="primary-button full" onClick={dismissReport}>{game.status==="response"?"Enter response phase":ended?"Open debrief":"Continue investigation"}<ArrowRight size={17}/></button>}</>}</DialogContent></Dialog>
    <Dialog open={rules} onOpenChange={setRules}><DialogContent className="game-dialog wide-dialog"><DialogHeader><div className="eyebrow">FIELD GUIDE</div><DialogTitle>Investigate. Decide. Recover.</DialogTitle><DialogDescription>A complete solo incident-response exercise with hidden information and operational consequences.</DialogDescription></DialogHeader><div className="rules-content"><div className="rules-grid">
      <section><h3>01 / Objective</h3><p>Reveal four hidden attack stages before the turn limit or impact reaches 100. Then make containment and recovery decisions. Your final grade weighs speed, impact and continuity.</p></section>
      <section><h3>02 / Procedures &amp; dice</h3><p>Play one available procedure per turn. Meet the selected difficulty threshold to succeed. Four randomly established procedures add +3. Events and decisions can modify the next roll.</p></section>
      <section><h3>03 / Hidden evidence</h3><p>The current intelligence is intentionally ambiguous. Success reveals one stage only if the selected source can detect it. A successful mismatch consumes time and increases impact.</p></section>
      <section><h3>04 / Evidence decisions</h3><p>Every discovery forces a tradeoff. Preserve and observe improves the next roll but raises impact. Disrupt immediately lowers impact but removes useful telemetry from the next action.</p></section>
      <section><h3>05 / Cooldowns &amp; injects</h3><p>Used procedures cool down for three intervening turns. Natural 1, natural 20 or three failed rolls draw an inject that can alter evidence, pressure or the investigation.</p></section>
      <section><h3>06 / Contain &amp; recover</h3><p>Finding the chain is not the end. Choose a containment approach and a recovery path. Each changes business impact, service continuity and the final outcome.</p></section>
    </div><section className="attribution"><h3>About this adaptation</h3><p>Inspired by Backdoors &amp; Breaches, created by Black Hills Information Security and Active Countermeasures. This unofficial adaptation is not affiliated with or endorsed by the creators. It uses original wording, fictional settings and a rule-based facilitator. It does not reproduce the commercial deck, official artwork or expansion content.</p><a href="https://www.blackhillsinfosec.com/wp-content/uploads/2024/03/BnB_VisualGuide_v2_03052024.pdf" target="_blank" rel="noreferrer">Read the official classic rules <ArrowRight size={14}/></a></section></div></DialogContent></Dialog>
    <Dialog open={debrief} onOpenChange={setDebrief}><DialogContent className="game-dialog wide-dialog"><DialogHeader><div className="eyebrow">AFTER-ACTION REVIEW</div><DialogTitle>{game?.status==="won"?`${getOutcome(game).grade} / ${getOutcome(game).title}`:game?.status==="exercise"?"Exercise concluded.":"The response window closed."}</DialogTitle><DialogDescription>{game?.status==="won"?getOutcome(game).detail:game?`${game.revealed.length} of 4 stages found in ${game.turns.length} turns. This is a learning outcome, not a security assessment.`:""}</DialogDescription></DialogHeader>{game&&<><div className="debrief-stats"><div><strong>{game.turns.filter(t=>t.success).length}/{game.turns.length}</strong><span>Rolls succeeded</span></div><div><strong>{game.impact}</strong><span>Final impact</span></div><div><strong>{game.continuity}</strong><span>Service continuity</span></div></div>{game.decisions.length>0&&<div className="decision-summary"><span className="eyebrow">YOUR DECISIONS</span>{game.decisions.map((d,i)=><p key={`${d.stage}-${i}`}><strong>{attacks.find(a=>a.id===d.stage)?.title}:</strong> {d.title} <span>{d.effect}</span></p>)}{game.responseChoices.map(id=>{const o=[...responseOptions.containment,...responseOptions.recovery].find(x=>x.id===id);return <p key={id}><strong>Response:</strong> {o?.title}</p>})}</div>}<div className="debrief-chain">{game.chain.map((id,i)=>{const a=attacks.find(a=>a.id===id)!;return <section key={id} style={{"--stage-color":stages[i].color} as React.CSSProperties}><span className="eyebrow">0{i+1} / {stages[i].name}<span className={game.revealed.includes(id)?"found-label":"missed-label"}>{game.revealed.includes(id)?"FOUND":"UNRESOLVED"}</span></span><h3>{a.title}</h3><p>{a.evidence}</p><small>Detectable with: {a.detect.map(id=>procedures.find(p=>p.id===id)?.title).join(" · ")}</small></section>})}</div><section className="debrief-learning"><h3>Take this back to your team</h3><p>{game.turns.some(t=>t.success&&!t.revealed)?"Some actions passed without finding new evidence. Did each action separate plausible explanations, or simply use an available tool?":"Which evidence sources or decision authorities would be weakest in a real response?"}</p><p>{activeScenario.lesson}</p></section><button className="primary-button full" onClick={()=>{setGame(null);setDebrief(false);setScenarioChoice((game.scenario+1)%scenarios.length)}}>Choose next incident <ArrowRight size={18}/></button></>}</DialogContent></Dialog>
    <AlertDialog open={newConfirm} onOpenChange={setNewConfirm}><AlertDialogContent className="game-dialog"><AlertDialogHeader><AlertDialogTitle>Leave this investigation?</AlertDialogTitle><AlertDialogDescription>Your current case and turn history will be cleared.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep investigating</AlertDialogCancel><AlertDialogAction onClick={()=>{setGame(null);setNewConfirm(false);setQuestion(null);setReport(null);setSelected(null)}}>Choose a new incident</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}

function ResponsePanel({game,onChoose}:{game:Game;onChoose:(choice:string)=>void}){
  const containment=game.responseChoices.length===0;const options=containment?responseOptions.containment:responseOptions.recovery;
  return <section className="response-panel"><div className="response-heading"><span className="response-icon">{containment?<Zap size={24}/>:<HeartPulse size={24}/>}</span><div><span className="eyebrow">{containment?"CONTAINMENT DECISION":"RECOVERY DECISION"}</span><h2>{containment?"The chain is known. Stop the active risk.":"The threat is constrained. Restore trusted service."}</h2><p>{containment?"There is no perfect choice. Balance attacker access, evidence and operational continuity.":"Choose how much confidence, time and disruption the organisation can accept."}</p></div></div><div className="response-options">{options.map(o=><button key={o.id} onClick={()=>onChoose(o.id)}><strong>{o.title}</strong><span>{o.description}</span><small>Impact {o.impact>0?"+":""}{o.impact} · Continuity {o.continuity>0?"+":""}{o.continuity}</small><ArrowRight size={17}/></button>)}</div></section>;
}
