import { Building2, HeartPulse, Factory, Ship, Cloud, Network, Landmark, RadioTower, Droplets, BadgeDollarSign } from "lucide-react";

export const stages = [
  {name:"Initial compromise",short:"Entry",color:"#ff967d"},
  {name:"Pivot & escalate",short:"Movement",color:"#e8c968"},
  {name:"Persistence",short:"Foothold",color:"#b49cf4"},
  {name:"C2 & exfiltration",short:"Outbound",color:"#75b9e7"},
];

export const procedures = [
  {id:"endpoint",title:"Endpoint analysis",short:"Processes, execution and host alerts",description:"Examine endpoint telemetry for unusual processes, parent-child relationships and changes to the host.",question:"Which process ran, under whose identity, and what changed?"},
  {id:"identity",title:"Identity audit",short:"Sign-ins, permissions and account changes",description:"Correlate authentication records, group membership and account changes across the identity platform.",question:"Are these sign-ins and privileges consistent with normal activity?"},
  {id:"network",title:"Network analysis",short:"Traffic patterns and east-west activity",description:"Review network flows and packet metadata to identify unusual destinations or movement between systems.",question:"Which systems communicated, and does that path make sense?"},
  {id:"firewall",title:"Firewall review",short:"Boundary connections and egress",description:"Inspect firewall sessions, blocked traffic and remote-access connection records at the relevant boundaries.",question:"What crossed the boundary, when, and in which direction?"},
  {id:"email",title:"Email investigation",short:"Messages, links and delivery traces",description:"Review message headers, delivery logs and suspicious attachments associated with the reported activity.",question:"Was a message or link used to establish the first foothold?"},
  {id:"server",title:"Server inspection",short:"Services, jobs and application logs",description:"Inspect server application logs, services and configuration changes for unexpected execution or access.",question:"Which server-side change or request explains the incident?"},
  {id:"cloud",title:"Cloud audit",short:"API activity, tokens and cloud roles",description:"Correlate control-plane audit events, workload identity activity and API permissions in the cloud environment.",question:"Which identity called which API, and from where?"},
  {id:"dns",title:"DNS review",short:"Lookups, new domains and beaconing",description:"Examine resolver records for repetitive lookups, unusual domains and encoded query patterns.",question:"Do the domain queries expose a communication channel?"},
  {id:"hunt",title:"Targeted threat hunt",short:"Cross-source hypothesis testing",description:"Test a specific hypothesis across endpoint and network telemetry to identify behaviour missed by alerts.",question:"What observable behaviour would confirm our current hypothesis?"},
  {id:"forensic",title:"Forensic triage",short:"Disk, memory and execution artefacts",description:"Collect and analyse preserved artefacts from a suspected host, including execution traces and configuration changes.",question:"What durable artefacts reconstruct how access was established or retained?"},
  {id:"intel",title:"Intelligence correlation",short:"Known infrastructure and indicators",description:"Compare observed destinations and suspicious artefacts against available threat intelligence, while checking context.",question:"Does known malicious infrastructure help explain our observations?"},
];

export type HypothesisId = "identity"|"endpoint"|"application"|"cloud";
export type Attack = {id:string;stage:number;title:string;detect:string[];vector:HypothesisId;clue:string;evidence:string};

// Seventy-two original techniques, eighteen per stage. Each technique carries the
// evidence sources that can expose it, so different scenarios draw meaningfully
// different procedures instead of the same small rotation.
export const attacks: Attack[] = [
  {id:"phish",stage:0,title:"Phishing attachment",detect:["email","endpoint","forensic"],vector:"endpoint",clue:"A document opened shortly before the first host anomaly.",evidence:"Message traces and process ancestry link a delivered attachment to the first malicious execution."},
  {id:"vpn",stage:0,title:"Stolen remote-access account",detect:["identity","firewall","network"],vector:"identity",clue:"A valid remote session falls outside its owner’s normal pattern.",evidence:"Remote-access records show a valid account used from an unfamiliar source without corresponding user activity."},
  {id:"web",stage:0,title:"Exploited public application",detect:["server","firewall","forensic"],vector:"application",clue:"Unusual application requests precede unexpected server execution.",evidence:"Application logs tie malformed requests to server-side execution at the start of the incident."},
  {id:"token",stage:0,title:"Exposed cloud credential",detect:["cloud","identity","hunt"],vector:"cloud",clue:"An automation identity is active outside its workload boundary.",evidence:"Cloud audit records show a workload credential used from outside the approved execution environment."},
  {id:"supply",stage:0,title:"Compromised software update",detect:["endpoint","network","intel"],vector:"endpoint",clue:"Several hosts changed soon after a trusted package was deployed.",evidence:"Package telemetry and process records connect a signed update path to malicious execution on multiple hosts."},
  {id:"oauth",stage:0,title:"Malicious application consent",detect:["identity","cloud","email"],vector:"identity",clue:"A user-approved application has begun reading data it never accessed before.",evidence:"Consent and API logs show a deceptive application receiving delegated access to the user’s data."},
  {id:"vpn-token",stage:0,title:"Replayed remote session",detect:["identity","firewall","hunt"],vector:"identity",clue:"One remote session appears from two source addresses minutes apart.",evidence:"A captured remote-access token is replayed to reopen an authenticated path without a fresh sign-in."},
  {id:"helpdesk",stage:0,title:"Help-desk reset abuse",detect:["identity","email","endpoint"],vector:"identity",clue:"A password reset was granted on a call that left no callback record.",evidence:"Service-desk and directory logs show a reset performed for a caller who could not be verified."},
  {id:"sideload",stage:0,title:"Sideloaded browser extension",detect:["endpoint","network","hunt"],vector:"endpoint",clue:"A workstation began reaching a new analytics domain after a browser change.",evidence:"Extension inventory and network records show a manually installed add-on relaying page content."},
  {id:"redirect",stage:0,title:"Credential phishing redirect",detect:["email","dns","server"],vector:"application",clue:"A campaign link resolved through an unfamiliar domain before a sign-in prompt.",evidence:"Mail, resolver and server records link a delivered link to a credential prompt on a look-alike domain."},
  {id:"removable",stage:0,title:"Removable-media infector",detect:["endpoint","forensic","intel"],vector:"endpoint",clue:"A host executed a file with no download or mail trail.",evidence:"Execution begins from removable media on a system with no corresponding download or message delivery."},
  {id:"mfa",stage:0,title:"Repeated MFA approvals",detect:["identity","email","firewall"],vector:"identity",clue:"A user accepted several unexpected authentication prompts in a row.",evidence:"Identity logs show the user approving a challenge generated by an unfamiliar sign-in attempt."},
  {id:"vendor",stage:0,title:"Vendor software push",detect:["server","firewall","network"],vector:"application",clue:"A supplier channel delivered a package outside its normal change window.",evidence:"A vendor update path is used to introduce unauthorised code outside any approved change."},
  {id:"apikey",stage:0,title:"Public API key abuse",detect:["cloud","network","dns"],vector:"cloud",clue:"A key found in public code is now calling from a new network.",evidence:"API records show a client key used far beyond its original application and address range."},
  {id:"share",stage:0,title:"Exposed file share write",detect:["server","forensic","network"],vector:"application",clue:"An internet-reachable share received an unexpected upload.",evidence:"A file written to an internet-reachable share is executed by the service that accepted the connection."},
  {id:"kiosk",stage:0,title:"Shared kiosk session takeover",detect:["identity","endpoint","firewall"],vector:"identity",clue:"A shared terminal stayed signed in to a privileged profile.",evidence:"A shared terminal's authenticated session is reused to drive interactive administration, with no matching sign-in by the named operator."},
  {id:"lapsed-vpn",stage:0,title:"Lapsed supplier VPN account",detect:["firewall","identity","intel"],vector:"identity",clue:"A dormant supplier account reconnected after its access should have ended.",evidence:"An account that was never disabled at the end of an engagement reconnects successfully."},
  {id:"resolver",stage:0,title:"Resolver redirection",detect:["dns","network","firewall"],vector:"application",clue:"Internal names began resolving to an address outside the estate.",evidence:"Internal service names are answered with attacker-controlled addresses instead of their own."},
  {id:"approver",stage:0,title:"Settlement approver takeover",detect:["identity","email","firewall"],vector:"identity",clue:"A settlement approver authenticates outside the window their delegation covers.",evidence:"A settlement approver's credentials were in use outside the hours their delegation covers, with no corresponding activity from the approver."},
  {id:"citizen-portal",stage:0,title:"Citizen portal credential reuse",detect:["identity","firewall","email"],vector:"identity",clue:"A citizen-facing account reaches functions only staff should hold.",evidence:"A citizen-facing credential reached staff-side functions it was never entitled to, through a portal that trusts one identity for both audiences."},
  {id:"spray",stage:1,title:"Internal password spraying",detect:["identity","network","hunt"],vector:"identity",clue:"Scattered authentication failures are followed by a few successes.",evidence:"A single internal source tries common passwords across many accounts, then authenticates successfully."},
  {id:"remote",stage:1,title:"Remote service execution",detect:["endpoint","network","server"],vector:"endpoint",clue:"An ordinary workstation is making unusual administrative connections.",evidence:"Remote administrative sessions create processes on additional systems from an ordinary workstation."},
  {id:"role",stage:1,title:"Cloud role escalation",detect:["cloud","identity","hunt"],vector:"cloud",clue:"A workload begins using resources beyond its normal permission boundary.",evidence:"An over-permissive role relationship lets the compromised identity assume an elevated cloud role."},
  {id:"dump",stage:1,title:"Credential theft from memory",detect:["endpoint","forensic","hunt"],vector:"endpoint",clue:"A process accessed authentication-related memory without a normal reason.",evidence:"Process-access records and memory artefacts show credential material extracted for additional access."},
  {id:"session",stage:1,title:"Session token replay",detect:["identity","cloud","network"],vector:"identity",clue:"The same user session appears in two incompatible locations.",evidence:"A captured session is replayed to reach services beyond the one it was issued for."},
  {id:"trust",stage:1,title:"Trusted service abuse",detect:["server","cloud","network"],vector:"application",clue:"A permitted service path is reaching systems outside its normal dependency map.",evidence:"A trusted integration is used to cross into an environment outside its dependency map."},
  {id:"kerberoast",stage:1,title:"Service ticket extraction",detect:["identity","forensic","network"],vector:"identity",clue:"A workstation requested service tickets for roles it never uses.",evidence:"Service tickets are requested for high-value roles the requesting system never uses, then reused elsewhere."},
  {id:"delegation",stage:1,title:"Delegation path abuse",detect:["identity","server","endpoint"],vector:"identity",clue:"A service account can now act for users far beyond its scope.",evidence:"Directory configuration and server access show an unapproved delegation relationship being exercised."},
  {id:"pivot",stage:1,title:"Internal port-forward pivot",detect:["network","firewall","endpoint"],vector:"endpoint",clue:"An internal host began listening on a port it does not normally serve.",evidence:"A local tunnel carries administrative traffic into a segment the host does not normally reach."},
  {id:"scheduled",stage:1,title:"Deployment job abuse",detect:["endpoint","server","cloud"],vector:"endpoint",clue:"A routine deployment job ran a task it never carried before.",evidence:"An automated deployment account runs commands across systems outside any release."},
  {id:"vault",stage:1,title:"Secret-vault escalation",detect:["cloud","forensic","intel"],vector:"cloud",clue:"A workload began reading secrets outside its assigned path.",evidence:"A workload identity retrieves secrets outside the paths it was ever scoped to hold."},
  {id:"implant",stage:1,title:"In-memory implant handoff",detect:["endpoint","forensic","hunt"],vector:"endpoint",clue:"A process held no file on disk but opened an outbound channel.",evidence:"Memory artefacts and host records show code loaded directly into a running process."},
  {id:"db-cred",stage:1,title:"Database credential reuse",detect:["server","forensic","email"],vector:"application",clue:"A reporting account began connecting from an application host.",evidence:"One reused credential authenticates to data stores across separate environments."},
  {id:"keyreuse",stage:1,title:"Trusted key reuse",detect:["identity","firewall","server"],vector:"identity",clue:"An administrative key authenticated from a host that never held it.",evidence:"A private key is copied to an unrelated system and used there for access."},
  {id:"snapshot",stage:1,title:"Cloud snapshot share",detect:["cloud","network","hunt"],vector:"cloud",clue:"A volume snapshot gained a sharing permission no change request explains.",evidence:"A disk image is shared to an account outside the organisation and copied."},
  {id:"ci",stage:1,title:"Pipeline runner hijack",detect:["cloud","endpoint","email"],vector:"cloud",clue:"A build runner began executing steps outside its repository.",evidence:"An automation token edits build jobs so they run attacker commands on the runner."},
  {id:"wmi",stage:1,title:"Remote management execution",detect:["endpoint","network","forensic"],vector:"endpoint",clue:"Administrative channels are launching processes on several hosts at once.",evidence:"Management calls create processes across systems with no administrative relationship."},
  {id:"proxy",stage:1,title:"Internal proxy relay",detect:["firewall","intel","dns"],vector:"application",clue:"Outbound traffic now leaves through an internal host that never forwarded before.",evidence:"A compromised system is relaying traffic on behalf of other hosts."},
  {id:"entitlement",stage:1,title:"Payment entitlement widening",detect:["identity","cloud","hunt"],vector:"identity",clue:"A payment limit was raised shortly before the cut-off.",evidence:"A payment entitlement was widened outside the change calendar, lifting one approver past the threshold that would otherwise require a second signature."},
  {id:"provisioning",stage:1,title:"Subscriber provisioning access",detect:["cloud","identity","network"],vector:"cloud",clue:"A provisioning account changes services in regions it does not support.",evidence:"A provisioning account altered subscriber service entries outside the regions it supports, through the same interface the service desk uses."},
  {id:"task",stage:2,title:"Malicious scheduled task",detect:["endpoint","server","forensic"],vector:"endpoint",clue:"The same unsigned process returns at regular intervals after termination.",evidence:"A newly created scheduled task relaunches the attacker’s payload at fixed intervals."},
  {id:"account",stage:2,title:"Hidden privileged account",detect:["identity","server","hunt"],vector:"identity",clue:"An unexplained account appears in a privileged group.",evidence:"Account-creation and group-change records establish an unapproved privileged identity controlled by the attacker."},
  {id:"webshell",stage:2,title:"Web-shell foothold",detect:["server","forensic","endpoint"],vector:"application",clue:"A recently modified server file launches unusual child processes.",evidence:"A server-side file accepts remote commands and keeps access available through the application."},
  {id:"key",stage:2,title:"Additional access key",detect:["cloud","identity","hunt"],vector:"cloud",clue:"A new programmatic credential lacks a corresponding change record.",evidence:"Cloud control-plane records show a second access key created to preserve attacker access."},
  {id:"service",stage:2,title:"Rogue system service",detect:["endpoint","server","forensic"],vector:"endpoint",clue:"A new service starts before users sign in and survives a reboot.",evidence:"Service configuration and execution artefacts reveal a persistent malicious binary."},
  {id:"federation",stage:2,title:"Federated trust backdoor",detect:["cloud","identity","server"],vector:"cloud",clue:"Authentication trust settings changed outside the maintenance window.",evidence:"Control-plane history shows a rogue federation relationship created to maintain privileged access."},
  {id:"logon",stage:2,title:"Logon script modification",detect:["endpoint","server","hunt"],vector:"endpoint",clue:"A sign-in now runs an extra command for every user on a host.",evidence:"A logon process launches an unsigned payload at every interactive sign-in."},
  {id:"registry",stage:2,title:"Registry autorun persistence",detect:["endpoint","intel","hunt"],vector:"endpoint",clue:"An execution key points to a file with no owner record.",evidence:"A launcher is restored at every system start from a persisted configuration entry."},
  {id:"timer",stage:2,title:"System timer unit",detect:["server","forensic","hunt"],vector:"application",clue:"A unit restarts an unfamiliar process after each reboot.",evidence:"A scheduled timer re-establishes access with no user present."},
  {id:"sshkey",stage:2,title:"Authorised key addition",detect:["identity","server","forensic"],vector:"identity",clue:"A server accepts a key that appears in no provisioning record.",evidence:"An added public key grants unattended administrative access."},
  {id:"role-trust",stage:2,title:"Cross-account role trust",detect:["cloud","identity","intel"],vector:"cloud",clue:"A role now trusts an external account that was never approved.",evidence:"Control-plane records show a modified trust policy admitting an attacker-controlled principal."},
  {id:"mailbox",stage:2,title:"Hidden mailbox rule",detect:["email","identity","hunt"],vector:"identity",clue:"Copies of selected messages are being forwarded without user knowledge.",evidence:"A mailbox rule forwards matched messages and hides them from their owner."},
  {id:"resolver-svc",stage:2,title:"Registered resolver service",detect:["dns","network","server"],vector:"application",clue:"A host began answering internal queries it never served.",evidence:"A host is answering internal name queries it was never authorised to serve, redirecting lookups to attacker-controlled addresses."},
  {id:"image",stage:2,title:"Rogue container image",detect:["cloud","server","forensic"],vector:"cloud",clue:"A registry hosts an image tag that was rebuilt without a commit.",evidence:"An altered container layer starts a hidden process at launch."},
  {id:"wmi-sub",stage:2,title:"Event subscription persistence",detect:["endpoint","hunt","forensic"],vector:"endpoint",clue:"A management subscription triggers on every system start.",evidence:"A permanent event consumer relaunches the payload whenever its trigger fires."},
  {id:"grant",stage:2,title:"Application grant persistence",detect:["cloud","identity","forensic"],vector:"identity",clue:"A dormant application regained delegated permissions.",evidence:"Consent and control-plane records show a persistent grant renewed to keep access."},
  {id:"githook",stage:2,title:"Repository hook persistence",detect:["server","cloud","intel"],vector:"application",clue:"Repository activity now runs an extra step on every push.",evidence:"A repository hook executes attacker code on the build server at every commit."},
  {id:"svc-key",stage:2,title:"Second service credential",detect:["cloud","forensic","email"],vector:"cloud",clue:"A service can authenticate with a credential created outside change control.",evidence:"Control-plane records show an additional long-lived key created to preserve access."},
  {id:"paysupport",stage:2,title:"Payment-support component tampering",detect:["server","intel","firewall"],vector:"application",clue:"A settlement-support component treats a narrow set of transactions differently.",evidence:"A payment-support component was altered so a narrow set of transactions bypasses the validation every other item in the batch receives."},
  {id:"routepolicy",stage:2,title:"Routing policy reinstatement",detect:["network","server","intel"],vector:"application",clue:"A routing policy returns after it is removed.",evidence:"A routing policy redirecting a narrow prefix range was reinstated after removal by a change job nobody scheduled."},
  {id:"https",stage:3,title:"Encrypted web exfiltration",detect:["network","firewall","intel"],vector:"application",clue:"A system repeatedly uploads data to a rarely used web destination.",evidence:"Egress records and destination correlation identify sustained uploads to attacker-controlled infrastructure."},
  {id:"dnsout",stage:3,title:"DNS covert channel",detect:["dns","network","hunt"],vector:"application",clue:"Resolver telemetry contains long, repetitive subdomains.",evidence:"High-entropy DNS queries carry encoded data to an externally controlled domain."},
  {id:"storage",stage:3,title:"Cloud storage export",detect:["cloud","network","firewall"],vector:"cloud",clue:"Bulk object reads coincide with an outbound transfer spike.",evidence:"Object-access and transfer records correlate bulk retrieval with export to an unapproved destination."},
  {id:"beacon",stage:3,title:"Periodic command beacon",detect:["network","dns","endpoint"],vector:"endpoint",clue:"Short outbound connections repeat at unusually consistent intervals.",evidence:"Time-series analysis identifies a periodic command channel to new external infrastructure."},
  {id:"saas",stage:3,title:"SaaS synchronisation abuse",detect:["cloud","identity","network"],vector:"identity",clue:"An approved synchronisation client suddenly moves far more data than usual.",evidence:"Application and identity logs show a legitimate integration used to export protected records."},
  {id:"deadrop",stage:3,title:"Public dead-drop channel",detect:["intel","network","firewall"],vector:"application",clue:"Hosts poll a common public service with an uncommon request pattern.",evidence:"Proxy and intelligence records reveal commands hidden in content on a public platform."},
  {id:"tunnel",stage:3,title:"Tunnelled remote console",detect:["network","firewall","server"],vector:"identity",clue:"A persistent encrypted session now links two internal systems.",evidence:"An interactive administrative console is carried over an established tunnel."},
  {id:"webhook",stage:3,title:"Approved webhook relay",detect:["cloud","server","email"],vector:"cloud",clue:"A trusted collaboration service began moving payloads at a new rate.",evidence:"Data is posted to an integration channel the attacker controls."},
  {id:"mailout",stage:3,title:"Mailbox export channel",detect:["email","forensic","identity"],vector:"identity",clue:"A mailbox began forwarding large attachments to an external address.",evidence:"Protected content is relayed outward through an approved mail path."},
  {id:"paste",stage:3,title:"Paste-service staging",detect:["intel","endpoint","network"],vector:"application",clue:"A workstation repeatedly retrieves content from a public text service.",evidence:"Commands and exfiltrated data are staged through a public paste site."},
  {id:"splitzip",stage:3,title:"Split archive upload",detect:["cloud","endpoint","forensic"],vector:"cloud",clue:"Object storage received many small parts with a common naming pattern.",evidence:"An archive is split into parts and uploaded to external storage below the size that would alert."},
  {id:"dns-txt",stage:3,title:"TXT record retrieval",detect:["dns","intel","forensic"],vector:"application",clue:"Resolvers query text records for domains with no business use.",evidence:"Data is retrieved from text records on domains the attacker registered for the purpose."},
  {id:"stream",stage:3,title:"Streaming service relay",detect:["firewall","forensic","email"],vector:"application",clue:"Outbound media traffic exceeds any known service need.",evidence:"Protected content is carried inside an allowed streaming session."},
  {id:"ssh-out",stage:3,title:"Outbound administrative tunnel",detect:["network","firewall","forensic"],vector:"endpoint",clue:"An internal server now opens administrative sessions to the internet.",evidence:"A reverse administrative tunnel gives interactive access from outside the estate."},
  {id:"git-out",stage:3,title:"Repository mirror export",detect:["server","cloud","intel"],vector:"cloud",clue:"A repository is being mirrored to an unapproved destination.",evidence:"Source and configuration are pushed to storage outside the organisation."},
  {id:"spool",stage:3,title:"Print spooler extraction",detect:["endpoint","server","intel"],vector:"endpoint",clue:"A server began writing documents it was not asked to print.",evidence:"Queued print documents are captured and stored for later removal."},
  {id:"physical",stage:3,title:"Physical media export",detect:["endpoint","forensic","intel"],vector:"endpoint",clue:"A host wrote a large archive to removable media outside business hours.",evidence:"Protected data is copied to portable storage attached to an authorised workstation."},
  {id:"cdn",stage:3,title:"Content delivery covert channel",detect:["dns","network","email"],vector:"application",clue:"Cache requests carry unusually regular, high-entropy parameters.",evidence:"Command data is hidden inside cache and content-delivery requests."},
  {id:"reconsuppress",stage:3,title:"Reconciliation suppression",detect:["server","intel","network"],vector:"application",clue:"A reconciliation report balances against a ledger that does not.",evidence:"Reconciliation output was suppressed for selected entries, so the settlement summary reports a balanced position the underlying ledger does not support."},
  {id:"record-export",stage:3,title:"Public record bulk export",detect:["server","network","intel"],vector:"application",clue:"A records interface returns far more than a caseworker would ask for.",evidence:"A records interface served bulk responses far beyond a caseworker's pattern, drawing citizen records across case boundaries in a single sweep."},
];

export type Scenario = {id:string;icon:typeof Building2;sector:string;title:string;summary:string;brief:string;scope:string;timeline:string;constraints:string;impact:string;lesson:string;leads:string[];choices:string[][];preferred:[string,string]};
export const scenarios: Scenario[] = [
  {id:"quiet-office",icon:Building2,sector:"ENTERPRISE IT",title:"The quiet intrusion",summary:"An ordinary morning. An unusual sign-in. A foothold hidden in the noise.",brief:"It is 08:40. Two staff report unusual workstation behaviour, while a routine check shows unexpected outbound traffic. Business applications still operate. Determine how access was gained and what followed.",scope:"Employee endpoints, identity services, remote access and internal application servers. Only simulated evidence is used.",timeline:"Reports began this morning. The evidence window covers the preceding 24 hours.",constraints:"Telemetry is incomplete. A successful action is not proof that an attack technique is absent.",impact:"Payroll and shared business applications remain available, but confidence in privileged identities is falling.",lesson:"Could your team connect an endpoint report, an identity event and outbound traffic without treating them as separate incidents?",leads:["Two weak signals overlap: a user complaint and an outbound-traffic anomaly. Neither identifies the entry point.","Authentication, endpoint and egress timestamps do not align cleanly. Establish which record is causal.","The attacker may be using a legitimate identity or a legitimate-looking process. Test one explanation at a time."],choices:[["phish","vpn","oauth"],["spray","dump","session"],["task","account","service"],["https","beacon","saas"]],preferred:["credential","rebuild"]},
  {id:"care-network",icon:HeartPulse,sector:"HEALTHCARE",title:"After the night shift",summary:"Clinical services remain live while unfamiliar activity spreads behind the scenes.",brief:"At a fictional hospital, overnight staff report a sluggish workstation and unfamiliar remote sessions. Patient-facing services remain available. Investigate without assuming shutdown is the safe first action.",scope:"Administrative endpoints, the support gateway, identity services and clinical application servers. Medical devices are outside this attack chain.",timeline:"The first anomalies occurred during the night shift. Records cover that shift and the previous working day.",constraints:"Clinical continuity matters. Isolation can reduce risk but may interrupt time-sensitive work.",impact:"Patient care is continuing. The greatest immediate risk is loss of access to supporting records and scheduling.",lesson:"Who would authorise isolation of a system supporting clinical work, and what evidence would they need?",leads:["A slow endpoint and unfamiliar remote sessions may share a cause, or may be unrelated operational noise.","Support accounts cross several services during the night shift. Some of that activity is expected.","The safest investigative path is not automatically the fastest containment path."],choices:[["supply","helpdesk","redirect"],["remote","kerberoast","pivot"],["logon","registry","mailbox"],["https","dns-txt","mailout"]],preferred:["credential","restore"]},
  {id:"power-support",icon:Factory,sector:"ENERGY / OT SUPPORT",title:"Beyond the gateway",summary:"A supplier session raises questions at the boundary of plant support systems.",brief:"A fictional power operator sees an unusual supplier session to its maintenance environment. A support server later makes unfamiliar connections. Generation remains stable. Reconstruct the support-system compromise.",scope:"Supplier remote access, the maintenance jump host, identity services and support servers. Controllers and safety systems are not in scope.",timeline:"The suspicious session started after the approved maintenance window. Review the next twelve hours.",constraints:"Investigation is read-only. Distinguish a support-system breach from a process-safety event.",impact:"Generation is stable, but support access cannot yet be trusted. A rushed shutdown could introduce its own operational risk.",lesson:"Could you revoke supplier access without losing essential operational support, and who owns that decision?",leads:["A supplier session and server traffic are correlated in time, but not yet proven to share an identity.","The support environment has legitimate remote administration that can resemble lateral movement.","Boundary records are strong; host telemetry on the jump server has gaps."],choices:[["vendor","lapsed-vpn","share"],["delegation","scheduled","proxy"],["timer","wmi-sub","githook"],["beacon","deadrop","tunnel"]],preferred:["monitor","rebuild"]},
  {id:"port-terminal",icon:Ship,sector:"MARITIME",title:"A terminal under watch",summary:"A booking portal anomaly arrives during a busy operating window.",brief:"A fictional container terminal reports unusual requests to its booking portal. Support staff then spot unexplained server activity. Vessel operations continue. Establish the attack chain before the window closes.",scope:"The booking portal, application servers, identity services and business network. Crane control systems are excluded.",timeline:"Portal anomalies began at 05:30, followed by internal activity during the morning shift.",constraints:"Busy operations hide suspicious traffic. Preserve evidence before disruptive changes.",impact:"Bookings continue, but partner data and vessel schedules may be exposed if the portal is not trustworthy.",lesson:"Which partners need early warning if an operational dependency can no longer be trusted?",leads:["A burst of portal requests could be partner traffic, automated abuse or exploitation.","Server activity follows the anomaly, but the available logs cannot yet prove direction of travel.","Partner identities and public application traffic overlap in the same time window."],choices:[["web","kiosk","vpn-token"],["trust","db-cred","keyreuse"],["webshell","resolver-svc","sshkey"],["https","dnsout","paste"]],preferred:["isolate","restore"]},
  {id:"cloud-control",icon:Cloud,sector:"CLOUD SERVICES",title:"An identity out of place",summary:"An automation account begins acting beyond its normal workload.",brief:"A fictional cloud provider detects unusual control-plane activity and an egress-cost spike. No scheduled deployment explains either. Investigate the identity, permission path and mechanism maintaining access.",scope:"Workload credentials, access management, control-plane logs and object-storage activity. No real cloud account is connected.",timeline:"The anomaly began several hours after the last approved deployment.",constraints:"Successful API calls can still be malicious. Attribute the caller before assuming the credential’s owner acted.",impact:"Customer workloads are online. Unchecked privilege expansion could expose multiple tenants and increase transfer costs.",lesson:"Could you rotate a compromised workload credential safely and identify every role and key derived from it?",leads:["Valid API calls and higher transfer volume are the only confirmed facts.","The credential owner, execution location and assumed role may be three different things.","A permission change can explain movement, persistence or normal deployment activity."],choices:[["token","apikey","mfa"],["role","vault","snapshot"],["key","federation","svc-key"],["storage","splitzip","webhook"]],preferred:["credential","rebuild"]},
  {id:"shared-services",icon:Network,sector:"DIGITAL INFRASTRUCTURE",title:"A trusted connection",summary:"A shared-service identity links an isolated alert to a wider incident.",brief:"A fictional shared-services operator sees an unfamiliar session under a trusted support identity. A dependent application later reports unexpected access. Service remains available, but scope is unclear.",scope:"Remote support, identity services, shared application servers and outbound records. Connected organisations are not directly accessible.",timeline:"Anomalies cluster around the last support window. Begin with the shared service’s own evidence.",constraints:"Do not assume trust extends across every connected service. Separate confirmed evidence from partner reports.",impact:"Dependent organisations still receive service, but each additional minute increases the chance of propagating bad trust decisions.",lesson:"What evidence can you share promptly, and how will you separate confirmed facts from assumptions?",leads:["A trusted identity appears in two environments, but only one side has complete telemetry.","The dependent application report may reveal scope, or may be a separate incident.","Trust relationships make legitimate administration and attacker movement look similar."],choices:[["resolver","removable","sideload"],["implant","wmi","ci"],["role-trust","image","resolver-svc"],["cdn","stream","dnsout"]],preferred:["credential","patch"]},
  {id:"government-service",icon:Landmark,sector:"GOVERNMENT DIGITAL SERVICE",title:"Authority under pressure",summary:"A privileged administrative identity appears across citizen-service systems.",brief:"A fictional government digital service detects anomalous privileged access shortly before a high-demand public transaction window. Services remain available, but the trust boundary is uncertain.",scope:"Administrative identities, citizen-service applications, shared hosting and outbound telemetry.",timeline:"The first privileged event occurred ninety minutes before the demand surge.",constraints:"Public access must be preserved where safe. Attribution is incomplete and multiple agencies depend on the platform.",impact:"A loss of trust could delay essential public transactions and trigger cross-agency coordination.",lesson:"How quickly can confirmed facts be shared without overstating scope?",leads:["A privileged action is confirmed, but the initiating identity may have been replayed.","Application and identity logs disagree on the apparent source.","A shared administrative path may connect otherwise separate services."],choices:[["citizen-portal","oauth","web"],["session","role","trust"],["account","federation","mailbox"],["record-export","git-out","storage"]],preferred:["credential","rebuild"]},
  {id:"telecom-core",icon:RadioTower,sector:"INFOCOMM",title:"Signals in the core",summary:"Management-plane activity overlaps with an emerging service-quality issue.",brief:"A fictional telecommunications provider observes unusual management access while customers report intermittent service degradation. Determine whether the events form one incident.",scope:"Management identities, support systems, network-management servers and egress records. Live customer traffic content is excluded.",timeline:"The access anomaly preceded service reports by forty minutes.",constraints:"Containment must avoid unnecessary loss of national connectivity.",impact:"Service remains broadly available, but further degradation could affect dependent essential services.",lesson:"Which control-plane actions require immediate joint cyber and operations authority?",leads:["A valid support session accessed an uncommon management path.","Service degradation may be operational noise or an attacker consequence.","The actor can hide inside legitimate administration at scale."],choices:[["vpn-token","token","vendor"],["provisioning","remote","trust"],["routepolicy","service","role-trust"],["beacon","ssh-out","cdn"]],preferred:["monitor","rebuild"]},
  {id:"water-operations",icon:Droplets,sector:"WATER / OT SUPPORT",title:"Pressure boundary",summary:"A support-system anomaly emerges while treatment operations remain stable.",brief:"A fictional water operator identifies an unapproved remote session and configuration access in an engineering support environment. Treatment remains within safe operating limits.",scope:"Remote support, engineering workstations, historian support and identity services. Process controllers remain read-only in this exercise.",timeline:"The session began after a vendor maintenance task was closed.",constraints:"Cyber actions must preserve safe and continuous water operations.",impact:"Operations are stable, but engineering trust and future maintenance confidence are degrading.",lesson:"Can the team distinguish compromise of engineering support from a process-safety event?",leads:["Vendor access remained active beyond its approved window.","A support workstation and historian show related but incomplete evidence.","An operationally safe response still requires decisive trust revocation."],choices:[["phish","helpdesk","kiosk"],["implant","dump","kerberoast"],["service","timer","sshkey"],["deadrop","spool","physical"]],preferred:["credential","restore"]},
  {id:"financial-clearing",icon:BadgeDollarSign,sector:"BANKING & FINANCE",title:"The clearing window",summary:"An identity anomaly appears before a time-sensitive settlement cycle.",brief:"A fictional financial institution detects unusual privileged activity and an unexpected export pattern before settlement processing. Determine the route without disrupting trusted transactions unnecessarily.",scope:"Privileged identities, payment-support applications, cloud workloads and outbound transfer records.",timeline:"Activity began two hours before the next settlement cycle.",constraints:"Integrity and availability matter equally. Decisions must be defensible under tight time pressure.",impact:"Transactions continue, but data integrity and settlement confidence could deteriorate rapidly.",lesson:"What evidence is sufficient to constrain access before a critical financial window?",leads:["A valid privileged identity initiated unusual but permitted activity.","The export pattern may be reconciliation traffic or staged data.","Application integrity must be tested alongside confidentiality risk."],choices:[["approver","vpn","apikey"],["entitlement","vault","session"],["paysupport","grant","key"],["reconsuppress","mailout","splitzip"]],preferred:["credential","rebuild"]},
];

export type Difficulty = "training"|"operational"|"crisis";
export const difficulties: Record<Difficulty,{title:string;description:string;threshold:number;maxTurns:number;startImpact:number}> = {
  training:{title:"Training",description:"More time, clearer margin for experimentation.",threshold:10,maxTurns:11,startImpact:14},
  operational:{title:"Operational",description:"Balanced uncertainty, pressure and time.",threshold:11,maxTurns:10,startImpact:22},
  crisis:{title:"Crisis",description:"Tighter rolls, fewer turns and higher starting impact.",threshold:12,maxTurns:9,startImpact:34},
};

export const hypotheses: {id:HypothesisId;title:string;premise:string;procedures:string[]}[] = [
  {id:"identity",title:"Identity-led intrusion",premise:"A valid account, session or trust relationship is carrying the activity — on the way in, while it moves, and when data leaves.",procedures:["identity","firewall","cloud","hunt","email"]},
  {id:"endpoint",title:"Compromised host",premise:"Code running on an endpoint or server is carrying the activity, from the first process to whatever it sends out.",procedures:["endpoint","forensic","server","hunt"]},
  {id:"application",title:"Application or supplier path",premise:"A public-facing service or internet-borne channel is carrying the activity — an exposed application or supplier package on the way in, the open web, DNS or a hosting service on the way out.",procedures:["server","network","firewall","intel","dns"]},
  {id:"cloud",title:"Cloud control-plane abuse",premise:"Tokens, roles and cloud services are being used outside their intended boundary, in the control plane and through its own storage and integrations.",procedures:["cloud","identity","network","hunt"]},
];

export const scenarioDynamics = [
  {label:"Business service integrity",objective:"Exploit trusted identities and quietly reach shared business data.",reaction:"The actor rotates to another trusted session after detecting intervention.",escalations:["A privileged session begins accessing an additional business service.","Payroll data is staged on an internal share.","A second administrator account shows anomalous activity."],countermeasure:"Earlier identity revocation would have reduced spread, but risked locking out legitimate administrators."},
  {label:"Clinical service continuity",objective:"Use support access to reach administrative records without triggering a clinical outage.",reaction:"The actor shifts activity into a different support account and reduces its request rate.",escalations:["The scheduling service begins responding slowly.","A clinical support queue moves to manual processing.","Staff report intermittent access to administrative records."],countermeasure:"A segmented support path would have limited movement while preserving most clinical activity."},
  {label:"Trusted maintenance access",objective:"Remain inside the support environment and abuse legitimate maintenance pathways.",reaction:"The actor abandons the observed session and moves toward a dormant supplier trust path.",escalations:["A maintenance job is delayed while access is verified.","The jump host can no longer be treated as a trusted administration point.","Operations invokes an alternate maintenance process."],countermeasure:"Revoking all supplier access earlier would have reduced cyber risk but weakened operational support."},
  {label:"Terminal service flow",objective:"Use the booking environment to obtain partner data and disrupt trusted transactions.",reaction:"The actor changes infrastructure and begins blending with partner-originated traffic.",escalations:["Partner bookings require additional verification.","A vessel schedule update enters a manual review queue.","The terminal activates a continuity process for partner transactions."],countermeasure:"Earlier portal isolation would have constrained access but caused a larger partner-service interruption."},
  {label:"Tenant trust",objective:"Expand control-plane privileges and export data through legitimate cloud services.",reaction:"The actor exchanges the observed credential for another role and changes the export path.",escalations:["A second tenant boundary requires urgent review.","Unplanned egress cost continues to rise.","The provider restricts one automation workflow pending validation."],countermeasure:"Broad credential rotation would have reduced attacker options but disrupted dependent automation."},
  {label:"Downstream trust",objective:"Propagate through shared identities before dependent organisations can coordinate.",reaction:"The actor lowers activity on the shared service and tests a downstream trust relationship.",escalations:["A dependent organisation requests urgent indicators.","Another connected service suspends automated trust.","Coordination delays leave one downstream environment without confirmed scope."],countermeasure:"Earlier partner notification could have reduced downstream exposure, while sharing less-certain information."},
  {label:"Public service integrity",objective:"Exploit privileged trust to reach multiple citizen-service applications.",reaction:"The actor shifts into a shared administrative identity and lowers its activity rate.",escalations:["A second public service reports anomalous administration.","Transaction queues begin to grow.","Cross-agency coordination moves to crisis posture."],countermeasure:"Earlier privilege restriction could have reduced spread but delayed legitimate public-service administration."},
  {label:"Connectivity continuity",objective:"Abuse management access while blending with legitimate operational change.",reaction:"The actor rotates to a dormant support path and changes its management endpoint.",escalations:["Service degradation expands to another region.","A dependent operator requests urgent assurance.","Network operations restrict nonessential changes."],countermeasure:"Earlier segmentation of management access could have constrained the actor with less customer disruption."},
  {label:"Treatment continuity",objective:"Preserve access to engineering support while approaching operational dependencies.",reaction:"The actor abandons the observed session and tests an older vendor credential.",escalations:["Engineering support enters manual verification.","A maintenance activity is deferred.","Operations increases monitoring of treatment tolerances."],countermeasure:"Earlier vendor-session revocation would have reduced risk while requiring an alternate maintenance process."},
  {label:"Settlement integrity",objective:"Use privileged and cloud access to alter or export sensitive transaction data.",reaction:"The actor exchanges the observed role for another trusted application path.",escalations:["A reconciliation discrepancy requires review.","Settlement staff activate enhanced verification.","A critical processing window approaches with unresolved scope."],countermeasure:"Earlier credential restriction could have reduced exposure while slowing legitimate settlement preparation."},
];

export function attackVector(id:string):HypothesisId {return attacks.find(attack=>attack.id===id)?.vector ?? "endpoint";}

type Inject = {id:string;title:string;text:string;effect:string;effectLabel:string;reason:string};
export type Turn = {number:number;procedure:string;raw:number;modifier:number;total:number;success:boolean;revealed:string|null;narrative:string;inject:Inject|null;injectReveal:string|null;impactChange:number};
export type DecisionRecord = {stage:string;choice:"preserve"|"disrupt";title:string;effect:string};
export type GameStatus = "playing"|"response"|"won"|"lost"|"exercise";
export type Game = {scenario:number;difficulty:Difficulty;chain:string[];revealed:string[];established:string[];lastUsed:Record<string,number>;turns:Turn[];failures:number;nextModifier:number;injectDeck:number[];status:GameStatus;impact:number;pendingDecision:string|null;decisions:DecisionRecord[];responseChoices:string[];responseScore:number;continuity:number};

export const responseOptions = {
  containment:[
    {id:"isolate",title:"Isolate affected systems",description:"Cuts attacker access quickly, but may interrupt service.",impact:-24,continuity:-14,score:12},
    {id:"credential",title:"Revoke identities and sessions",description:"Constrains identity-led movement with moderate operational disruption.",impact:-17,continuity:-5,score:11},
    {id:"monitor",title:"Monitor while mapping scope",description:"Preserves visibility and continuity, but allows risk to persist.",impact:5,continuity:5,score:9},
  ],
  recovery:[
    {id:"rebuild",title:"Rebuild from trusted baseline",description:"Highest confidence, longest service interruption.",impact:-18,continuity:-13,score:14},
    {id:"restore",title:"Restore validated backups",description:"Faster recovery if backup integrity is sound.",impact:-12,continuity:2,score:11},
    {id:"patch",title:"Patch in place and monitor",description:"Fastest return, with more residual uncertainty.",impact:-6,continuity:8,score:7},
  ],
};

export function randomInt(max:number) {if(typeof crypto!=="undefined"&&crypto.getRandomValues){const limit=Math.floor(0x100000000/max)*max;const value=new Uint32Array(1);do{crypto.getRandomValues(value)}while(value[0]>=limit);return value[0]%max;}return Math.floor(Math.random()*max);}
