import { Building2, HeartPulse, Factory, Ship, Cloud, Network, Landmark, RadioTower, Droplets, BadgeDollarSign } from "lucide-react";

export const stages = [
  {name:"Initial compromise",short:"Entry",color:"#ff967d"},
  {name:"Pivot & escalate",short:"Movement",color:"#e8c968"},
  {name:"Persistence",short:"Foothold",color:"#b49cf4"},
  {name:"C2 & exfiltration",short:"Outbound",color:"#75b9e7"},
];

export const procedures = [
  {id:"endpoint",title:"Endpoint analysis",short:"Programs running on computers, and their alerts",description:"Examine endpoint telemetry for unusual processes, parent-child relationships and changes to the host.",question:"Which process ran, under whose identity, and what changed?"},
  {id:"identity",title:"Identity audit",short:"Sign-ins, permissions and account changes",description:"Correlate authentication records, group membership and account changes across the identity platform.",question:"Are these sign-ins and privileges consistent with normal activity?"},
  {id:"network",title:"Network analysis",short:"Traffic between systems inside the network",description:"Review network flows and packet metadata to identify unusual destinations or movement between systems.",question:"Which systems communicated, and does that path make sense?"},
  {id:"firewall",title:"Firewall review",short:"Connections in and out at the network edge",description:"Inspect firewall sessions, blocked traffic and remote-access connection records at the relevant boundaries.",question:"What crossed the boundary, when, and in which direction?"},
  {id:"email",title:"Email investigation",short:"Messages, links and delivery traces",description:"Review message headers, delivery logs and suspicious attachments associated with the reported activity.",question:"Did a message or link carry this part of the activity?"},
  {id:"server",title:"Server inspection",short:"Server logs, services and scheduled jobs",description:"Inspect server application logs, services and configuration changes for unexpected execution or access.",question:"Which server-side change or request explains the incident?"},
  {id:"cloud",title:"Cloud audit",short:"Cloud keys, roles and activity logs",description:"Correlate control-plane audit events, workload identity activity and API permissions in the cloud environment.",question:"Which identity called which API, and from where?"},
  {id:"dns",title:"DNS review",short:"Name lookups and newly seen web domains",description:"Examine resolver records for repetitive lookups, unusual domains and encoded query patterns.",question:"Do the domain queries expose a communication channel?"},
  {id:"hunt",title:"Targeted threat hunt",short:"A search across sources for your reading",description:"Test a specific hypothesis across endpoint, network, identity and cloud telemetry to identify behaviour missed by alerts.",question:"What observable behaviour would confirm our current hypothesis?"},
  {id:"forensic",title:"Forensic triage",short:"Close examination of a computer's disk and memory",description:"Collect and analyse preserved artefacts from a suspected host, including execution traces and configuration changes.",question:"What durable artefacts reconstruct how access was established or retained?"},
  {id:"intel",title:"Intelligence correlation",short:"Comparison with known attacker addresses and tools",description:"Compare observed destinations and suspicious artefacts against available threat intelligence, while checking context.",question:"Does known malicious infrastructure help explain our observations?"},
];

export type HypothesisId = "identity"|"endpoint"|"application"|"cloud";
export type Attack = {id:string;stage:number;title:string;detect:string[];vector:HypothesisId;clue:string;evidence:string};

// Seventy-two original techniques, eighteen per stage. Each technique carries the
// evidence sources that can expose it, so different scenarios draw meaningfully
// different procedures instead of the same small rotation.
export const attacks: Attack[] = [
  {id:"phish",stage:0,title:"Phishing attachment",detect:["email","endpoint","forensic"],vector:"endpoint",clue:"A document was opened just before the first computer started behaving strangely.",evidence:"A delivered attachment launched the first malicious program when it was opened."},
  {id:"vpn",stage:0,title:"Stolen remote-access account",detect:["identity","firewall","network"],vector:"identity",clue:"A valid remote session falls outside its owner’s normal pattern.",evidence:"A valid remote-access account was used from an unfamiliar source with no matching activity from its owner."},
  {id:"web",stage:0,title:"Exploited public application",detect:["server","firewall","forensic"],vector:"application",clue:"Odd requests to a public website came just before its server started running unexpected programs.",evidence:"Malformed requests to the public application led to the server running attacker commands at the start of the incident."},
  {id:"token",stage:0,title:"Exposed cloud credential",detect:["cloud","identity","hunt"],vector:"cloud",clue:"A key an automated cloud job runs under is being used from outside that job's environment.",evidence:"A workload credential was used from outside its approved execution environment."},
  {id:"supply",stage:0,title:"Compromised software update",detect:["endpoint","network","intel"],vector:"endpoint",clue:"Several computers changed soon after a trusted package was deployed.",evidence:"A signed software update delivered malicious code that ran on several computers."},
  {id:"oauth",stage:0,title:"Malicious application consent",detect:["identity","cloud","email"],vector:"identity",clue:"A user-approved application has begun reading data it never accessed before.",evidence:"A deceptive application was granted delegated access to the user’s data."},
  {id:"vpn-token",stage:0,title:"Replayed remote session",detect:["identity","firewall","hunt"],vector:"identity",clue:"One remote session appears from two source addresses minutes apart.",evidence:"A captured remote-access token is replayed to reopen an authenticated path without a fresh sign-in."},
  {id:"helpdesk",stage:0,title:"Help-desk reset abuse",detect:["identity","email","hunt"],vector:"identity",clue:"A password reset was granted on a call that left no callback record.",evidence:"A password reset was performed for a caller who could not be verified."},
  {id:"sideload",stage:0,title:"Sideloaded browser extension",detect:["endpoint","network","hunt"],vector:"endpoint",clue:"A workstation began reaching a new analytics domain after a browser change.",evidence:"A manually installed browser add-on is relaying page content outside the organisation."},
  {id:"redirect",stage:0,title:"Credential phishing redirect",detect:["email","dns","firewall","downtime-check"],vector:"application",clue:"A link in an email led through an unfamiliar web address to a sign-in page.",evidence:"A delivered link led through a look-alike domain to a credential prompt that captured the user's password."},
  {id:"removable",stage:0,title:"Removable-media infector",detect:["endpoint","forensic","intel"],vector:"endpoint",clue:"A computer executed a file with no download or mail trail.",evidence:"Execution begins from removable media on a system with no corresponding download or message delivery."},
  {id:"mfa",stage:0,title:"Repeated MFA approvals",detect:["identity","hunt","firewall"],vector:"identity",clue:"A user accepted several unexpected authentication prompts in a row.",evidence:"The user approved a sign-in challenge generated by an unfamiliar sign-in attempt."},
  {id:"vendor",stage:0,title:"Vendor software push",detect:["server","firewall","network"],vector:"application",clue:"A supplier's update arrived outside the agreed time for changes.",evidence:"A vendor update path is used to introduce unauthorised code outside any approved change."},
  {id:"apikey",stage:0,title:"Public API key abuse",detect:["cloud","identity","hunt"],vector:"cloud",clue:"A key found in public code is now calling from a new network.",evidence:"A client key is being used far beyond its original application and address range."},
  {id:"share",stage:0,title:"Exposed file share write",detect:["server","forensic","network"],vector:"application",clue:"A shared folder reachable from the internet received an unexpected upload.",evidence:"A file written to an internet-reachable share is executed by the service that accepted the connection."},
  {id:"kiosk",stage:0,title:"Shared kiosk session takeover",detect:["identity","endpoint","firewall"],vector:"identity",clue:"A shared terminal stayed signed in to a privileged profile.",evidence:"A shared terminal's authenticated session is reused to drive interactive administration, with no matching sign-in by the named operator."},
  {id:"lapsed-vpn",stage:0,title:"Lapsed supplier VPN account",detect:["firewall","identity","intel"],vector:"identity",clue:"A dormant supplier account reconnected after its access should have ended.",evidence:"An account that was never disabled at the end of an engagement reconnects successfully."},
  {id:"resolver",stage:0,title:"Resolver redirection",detect:["dns","network","firewall"],vector:"application",clue:"Internal system names began pointing to an address outside the organisation.",evidence:"Internal service names are answered with attacker-controlled addresses instead of their own."},
  {id:"approver",stage:0,title:"Settlement approver takeover",detect:["identity","email","firewall"],vector:"identity",clue:"A payment approver signs in outside the hours their authority covers.",evidence:"A settlement approver's credentials were in use outside the hours their delegation covers, with no corresponding activity from the approver."},
  {id:"citizen-portal",stage:0,title:"Citizen portal credential reuse",detect:["identity","firewall","email"],vector:"identity",clue:"A citizen-facing account reaches functions only staff should hold.",evidence:"A citizen-facing credential reached staff-side functions it was never entitled to, through a portal that trusts one identity for both audiences."},
  {id:"engineer-vpn",stage:0,title:"Engineering workstation remote access",detect:["identity","firewall","endpoint"],vector:"identity",clue:"An engineering workstation is reached remotely outside any maintenance window.",evidence:"An engineering workstation was reached over remote access outside every scheduled maintenance window, using an account that normally only works on site."},
  {id:"joiner",stage:0,title:"Unclaimed joiner account",detect:["identity","email","hunt","change-review"],vector:"identity",clue:"An account provisioned for a new starter is active before their first day.",evidence:"An account provisioned ahead of a new starter was active before the joiner ever collected it, from a location unrelated to their office."},
  {id:"pcs-cred",stage:0,title:"Port community system credential",detect:["identity","firewall","intel"],vector:"identity",clue:"A shipping-line account submits for a line it does not represent.",evidence:"A port community account submitted on behalf of a shipping line it has no agency agreement with, through the trust every party in the community shares."},
  {id:"id-broker",stage:0,title:"National identity broker assertion",detect:["identity","cloud","email","federation-review"],vector:"identity",clue:"The national sign-in service vouches for a citizen on a service they never opened.",evidence:"An identity assertion was issued for a service the citizen never opened, accepted downstream because every agency trusts the broker rather than the request."},
  {id:"spray",stage:1,title:"Internal password spraying",detect:["identity","network","hunt"],vector:"identity",clue:"Many failed sign-ins across different accounts are followed by a few that succeed.",evidence:"A single internal source tries common passwords across many accounts, then authenticates successfully."},
  {id:"remote",stage:1,title:"Remote service execution",detect:["endpoint","network","server"],vector:"endpoint",clue:"An ordinary workstation is making unusual administrative connections.",evidence:"Remote administrative sessions create processes on additional systems from an ordinary workstation."},
  {id:"role",stage:1,title:"Cloud role escalation",detect:["cloud","identity","hunt"],vector:"cloud",clue:"A workload begins using resources beyond its normal permission boundary.",evidence:"An over-permissive role relationship lets the compromised identity assume an elevated cloud role."},
  {id:"dump",stage:1,title:"Credential theft from memory",detect:["endpoint","forensic","hunt"],vector:"endpoint",clue:"A program read the part of a computer's memory that holds passwords, for no normal reason.",evidence:"Credential material was extracted from a running process to gain additional access."},
  {id:"session",stage:1,title:"Session token replay",detect:["identity","cloud","network"],vector:"identity",clue:"The same user session appears in two incompatible locations.",evidence:"A captured session is replayed to reach services beyond the one it was issued for."},
  {id:"trust",stage:1,title:"Trusted service abuse",detect:["server","cloud","network"],vector:"application",clue:"An approved connection between applications is reaching systems it never normally talks to.",evidence:"A trusted integration is used to cross into an environment outside its dependency map."},
  {id:"kerberoast",stage:1,title:"Service ticket extraction",detect:["identity","forensic","network"],vector:"identity",clue:"A workstation requested access passes for services its user never uses.",evidence:"Service tickets were requested in bulk for service accounts the requesting user never uses, so their passwords can be cracked offline."},
  {id:"delegation",stage:1,title:"Delegation path abuse",detect:["identity","server","endpoint","work-order"],vector:"identity",clue:"An account a service runs under can now act on behalf of far more users than it should.",evidence:"An unapproved delegation relationship is being used to act on another account's behalf."},
  {id:"pivot",stage:1,title:"Internal port-forward pivot",detect:["network","firewall","endpoint"],vector:"endpoint",clue:"An internal computer began accepting connections on a channel it does not normally offer.",evidence:"A local tunnel carries administrative traffic into a segment the host does not normally reach."},
  {id:"scheduled",stage:1,title:"Deployment job abuse",detect:["endpoint","server","cloud","work-order"],vector:"endpoint",clue:"A routine deployment job ran a task it never carried before.",evidence:"An automated deployment account runs commands across systems outside any release."},
  {id:"vault",stage:1,title:"Secret-vault escalation",detect:["cloud","identity","hunt"],vector:"cloud",clue:"A cloud workload began reading stored secrets outside the path it was assigned.",evidence:"A workload identity retrieves secrets outside the paths it was ever scoped to hold."},
  {id:"implant",stage:1,title:"In-memory implant handoff",detect:["endpoint","forensic","hunt"],vector:"endpoint",clue:"A program running only in memory, with no file on disk, opened a connection to the outside.",evidence:"Code was loaded directly into a running process, leaving nothing on disk."},
  {id:"db-cred",stage:1,title:"Database credential reuse",detect:["server","forensic","network"],vector:"application",clue:"The reporting database is being queried from an application server that never used it before.",evidence:"One reused credential authenticates to data stores across separate environments."},
  {id:"keyreuse",stage:1,title:"Trusted key reuse",detect:["identity","firewall","server"],vector:"identity",clue:"An administrator's login key was used from a computer that never held it.",evidence:"A private key is copied to an unrelated system and used there for access."},
  {id:"snapshot",stage:1,title:"Cloud snapshot share",detect:["cloud","identity","hunt","plane-replay"],vector:"cloud",clue:"A copy of a cloud server's disk was attached to a new machine with no change request behind it.",evidence:"A disk snapshot was copied and attached to a new instance inside the account, and the credentials stored on it were read."},
  {id:"ci",stage:1,title:"Pipeline runner hijack",detect:["cloud","endpoint","email"],vector:"cloud",clue:"A cloud build runner began executing steps outside its repository.",evidence:"Build jobs were edited to run commands of the operator's choosing on the shared runner, using an automation token rather than a person's account."},
  {id:"wmi",stage:1,title:"Remote management execution",detect:["endpoint","network","forensic"],vector:"endpoint",clue:"Admin tools are starting programs on several computers at once.",evidence:"Management calls create processes across systems with no administrative relationship."},
  {id:"proxy",stage:1,title:"Internal proxy relay",detect:["firewall","intel","dns"],vector:"application",clue:"Outbound traffic now leaves through an internal computer that never relayed traffic before.",evidence:"A compromised system is relaying traffic on behalf of other hosts."},
  {id:"entitlement",stage:1,title:"Payment entitlement widening",detect:["identity","cloud","hunt"],vector:"identity",clue:"A payment limit was raised shortly before the cut-off.",evidence:"A payment entitlement was widened outside the change calendar, lifting one approver past the threshold that would otherwise require a second signature."},
  {id:"provisioning",stage:1,title:"Subscriber provisioning access",detect:["cloud","identity","network","route-compare"],vector:"cloud",clue:"A cloud account that sets up customer services is changing regions it does not support.",evidence:"A provisioning account altered subscriber service entries outside the regions it supports, through the same interface the service desk uses."},
  {id:"historian",stage:1,title:"Historian query pivot",detect:["server","endpoint","forensic","historian-recon"],vector:"endpoint",clue:"The plant's process history is being searched far beyond what a shift report needs.",evidence:"Process history was queried far beyond any shift report, enumerating tag names and asset layout rather than reading values."},
  {id:"printqueue",stage:1,title:"Print service lateral movement",detect:["endpoint","forensic","server"],vector:"endpoint",clue:"A printing program is running on computers that have no printers.",evidence:"The print service was running on systems that hold no print queue, reaching them through a service everyone trusts and nobody watches."},
  {id:"tos-access",stage:1,title:"Terminal operating system access",detect:["endpoint","forensic","hunt","manifest-recon"],vector:"endpoint",clue:"Yard moves are queried from a workstation that never plans them.",evidence:"Container yard positions and crane allocations were queried from a workstation with no planning role, reading the operating system that runs the quay."},
  {id:"mgmt-platform",stage:1,title:"Shared management platform pivot",detect:["identity","server","cloud","propagation"],vector:"identity",clue:"One management console reaches customers it was never assigned.",evidence:"A shared management console was used to reach customer estates outside its assignment, because the platform that administers every tenant trusts one operator identity."},
  {id:"task",stage:2,title:"Malicious scheduled task",detect:["endpoint","server","forensic"],vector:"endpoint",clue:"The same unverified program comes back at regular intervals after it is stopped.",evidence:"A newly created scheduled task relaunches the attacker’s payload at fixed intervals."},
  {id:"account",stage:2,title:"Hidden privileged account",detect:["identity","server","hunt"],vector:"identity",clue:"An unexplained account appears in a privileged group.",evidence:"An unapproved privileged account controlled by the attacker was created and added to an administrative group."},
  {id:"webshell",stage:2,title:"Web-shell foothold",detect:["server","forensic","endpoint"],vector:"application",clue:"A recently changed file on a web server starts unusual programs.",evidence:"A server-side file accepts remote commands and keeps access available through the application."},
  {id:"key",stage:2,title:"Additional access key",detect:["cloud","identity","hunt"],vector:"cloud",clue:"A new cloud access key for scripts and tools has no change record behind it.",evidence:"A second access key was created to preserve attacker access."},
  {id:"service",stage:2,title:"Rogue system service",detect:["endpoint","server","forensic"],vector:"endpoint",clue:"A new service starts before users sign in and survives a reboot.",evidence:"A malicious program was installed as a service so that it restarts with the machine."},
  {id:"federation",stage:2,title:"Federated trust backdoor",detect:["cloud","identity","server"],vector:"cloud",clue:"The cloud account's rules for trusting outside sign-ins changed outside the maintenance window.",evidence:"A rogue federation relationship was created to keep privileged access to the cloud estate."},
  {id:"logon",stage:2,title:"Logon script modification",detect:["endpoint","server","hunt","downtime-check"],vector:"endpoint",clue:"A sign-in now runs an extra command for every user on a host.",evidence:"A logon process launches an unsigned payload at every interactive sign-in."},
  {id:"registry",stage:2,title:"Registry autorun persistence",detect:["endpoint","intel","hunt"],vector:"endpoint",clue:"A computer's start-up settings now launch a program with no owner record.",evidence:"A launcher is restored at every system start from a persisted configuration entry."},
  {id:"timer",stage:2,title:"System timer unit",detect:["server","forensic","hunt"],vector:"endpoint",clue:"A scheduled timer on a server restarts an unfamiliar program after each reboot.",evidence:"A scheduled timer re-establishes access with no user present."},
  {id:"sshkey",stage:2,title:"Authorised key addition",detect:["hunt","server","forensic"],vector:"identity",clue:"A server accepts a key that appears in no provisioning record.",evidence:"An added public key grants unattended administrative access."},
  {id:"role-trust",stage:2,title:"Cross-account role trust",detect:["cloud","identity","intel"],vector:"cloud",clue:"A cloud role can now be used by an outside cloud account that was never approved.",evidence:"A cloud trust policy was changed to admit an attacker-controlled identity."},
  {id:"mailbox",stage:2,title:"Hidden mailbox rule",detect:["email","identity","hunt"],vector:"identity",clue:"Copies of selected messages are being forwarded without user knowledge.",evidence:"A mailbox rule forwards matched messages and hides them from their owner."},
  {id:"resolver-svc",stage:2,title:"Registered resolver service",detect:["dns","network","server"],vector:"application",clue:"A computer began answering internal name lookups it never handled before.",evidence:"A host is answering internal name queries it was never authorised to serve, redirecting lookups to attacker-controlled addresses."},
  {id:"image",stage:2,title:"Rogue container image",detect:["cloud","server","forensic"],vector:"cloud",clue:"A cloud software image was rebuilt with no matching code change.",evidence:"An altered container layer starts a hidden process at launch."},
  {id:"wmi-sub",stage:2,title:"Event subscription persistence",detect:["endpoint","hunt","forensic"],vector:"endpoint",clue:"A hidden management task on a computer runs every time the system starts.",evidence:"A permanent event consumer relaunches the payload whenever its trigger fires."},
  {id:"grant",stage:2,title:"Application grant persistence",detect:["cloud","identity","email"],vector:"identity",clue:"An unused application was given back permission to act for users.",evidence:"A persistent application grant was renewed to keep access."},
  {id:"githook",stage:2,title:"Repository hook persistence",detect:["server","cloud","intel"],vector:"application",clue:"Every code change saved to the repository now runs an extra step.",evidence:"A repository hook executes attacker code on the build server at every commit."},
  {id:"svc-key",stage:2,title:"Second service credential",detect:["cloud","forensic","email","plane-replay"],vector:"cloud",clue:"A cloud service has a second access key that no change request created.",evidence:"An extra long-lived cloud key was created to preserve access."},
  {id:"paysupport",stage:2,title:"Payment-support component tampering",detect:["server","intel","firewall"],vector:"application",clue:"A settlement-support component treats a narrow set of transactions differently.",evidence:"A payment-support component was altered so a narrow set of transactions bypasses the validation every other item in the batch receives."},
  {id:"routepolicy",stage:2,title:"Routing policy reinstatement",detect:["network","server","intel","route-compare"],vector:"application",clue:"A routing policy returns after it is removed.",evidence:"A routing policy redirecting a narrow prefix range was reinstated after removal by a change job nobody scheduled."},
  {id:"engstation",stage:2,title:"Engineering station persistence",detect:["endpoint","forensic","hunt","historian-recon"],vector:"endpoint",clue:"An engineering station reloads a component after it is removed.",evidence:"An engineering station reinstated a removed component at startup, surviving the rebuild the support team believed had cleared it."},
  {id:"gpo",stage:2,title:"Policy object persistence",detect:["identity","server","forensic","change-review"],vector:"identity",clue:"A management policy re-applies a setting nobody requested.",evidence:"A management policy re-applied a setting no change record covers, restoring access on every machine in scope each time the policy runs."},
  {id:"gov-platform",stage:2,title:"Shared government platform persistence",detect:["identity","forensic","hunt","federation-review"],vector:"identity",clue:"A component used by several agencies reinstates an account after removal.",evidence:"A component several agencies share reinstated a privileged account after removal, so clearing it in one department restored it in the rest."},
  {id:"backbone",stage:2,title:"Backbone dependency persistence",detect:["network","dns","intel","propagation"],vector:"application",clue:"A lookup service every customer relies on keeps returning an extra entry.",evidence:"A dependency every downstream customer resolves kept answering with an added record after the change was reverted, reinstated from configuration rather than memory."},
  {id:"https",stage:3,title:"Encrypted web exfiltration",detect:["network","firewall","intel"],vector:"application",clue:"A system repeatedly uploads data to a rarely used web destination.",evidence:"Data was uploaded steadily over encrypted web traffic to attacker-controlled infrastructure."},
  {id:"dnsout",stage:3,title:"DNS covert channel",detect:["dns","network","hunt"],vector:"application",clue:"Name lookups ask for long, repetitive, random-looking web addresses.",evidence:"High-entropy DNS queries carry encoded data to an externally controlled domain."},
  {id:"storage",stage:3,title:"Cloud storage export",detect:["cloud","network","firewall"],vector:"cloud",clue:"Large reads from cloud storage coincide with a spike in outbound transfers.",evidence:"Bulk reads from cloud storage were exported to an unapproved destination."},
  {id:"beacon",stage:3,title:"Periodic command beacon",detect:["network","dns","endpoint"],vector:"endpoint",clue:"Short outbound connections repeat at unusually consistent intervals.",evidence:"A program calls out to new external infrastructure at regular intervals to collect commands."},
  {id:"saas",stage:3,title:"SaaS synchronisation abuse",detect:["cloud","identity","network"],vector:"identity",clue:"A staff account's approved file-sync connection suddenly moves far more data than usual.",evidence:"A legitimate integration is being used to export protected records."},
  {id:"deadrop",stage:3,title:"Public dead-drop channel",detect:["intel","network","firewall"],vector:"application",clue:"Computers keep checking a popular public website in an unusual pattern.",evidence:"Commands are being collected from content posted on a public platform."},
  {id:"tunnel",stage:3,title:"Tunnelled remote console",detect:["firewall","identity","network"],vector:"identity",clue:"An encrypted session from outside the organisation is held open under a valid support account.",evidence:"An interactive administrative console is carried over an established tunnel."},
  {id:"webhook",stage:3,title:"Approved webhook relay",detect:["cloud","server","email"],vector:"cloud",clue:"A cloud integration with a trusted collaboration service began moving data at a new rate.",evidence:"Data is posted to an integration channel the attacker controls."},
  {id:"mailout",stage:3,title:"Mailbox export channel",detect:["email","forensic","identity"],vector:"identity",clue:"A mailbox began forwarding large attachments to an external address.",evidence:"Protected content is relayed outward through an approved mail path."},
  {id:"paste",stage:3,title:"Paste-service staging",detect:["intel","endpoint","network"],vector:"application",clue:"A workstation repeatedly retrieves content from a public text service.",evidence:"Commands and exfiltrated data are staged through a public paste site."},
  {id:"splitzip",stage:3,title:"Split archive upload",detect:["cloud","endpoint","forensic"],vector:"cloud",clue:"Cloud storage received many small file pieces with matching names.",evidence:"An archive was split into parts below the alerting size, staged in the organisation's own cloud storage and shared out by public link."},
  {id:"dns-txt",stage:3,title:"TXT record retrieval",detect:["dns","intel","forensic"],vector:"application",clue:"Name lookups fetch text entries for web domains the business never uses.",evidence:"Data is retrieved from text records on domains the attacker registered for the purpose."},
  {id:"stream",stage:3,title:"Streaming service relay",detect:["firewall","forensic","network"],vector:"application",clue:"Outbound media traffic exceeds any known service need.",evidence:"Protected content is carried inside an allowed streaming session."},
  {id:"ssh-out",stage:3,title:"Outbound administrative tunnel",detect:["network","firewall","forensic"],vector:"endpoint",clue:"An internal server now opens administrative sessions to the internet.",evidence:"A reverse administrative tunnel gives interactive access from outside the estate."},
  {id:"git-out",stage:3,title:"Repository mirror export",detect:["server","cloud","intel"],vector:"cloud",clue:"A repository is being mirrored to an unapproved destination.",evidence:"Source and configuration are pushed to storage outside the organisation."},
  {id:"spool",stage:3,title:"Print spooler extraction",detect:["endpoint","server","intel"],vector:"endpoint",clue:"A server began writing documents it was not asked to print.",evidence:"Queued print documents are captured and stored for later removal."},
  {id:"physical",stage:3,title:"Physical media export",detect:["endpoint","forensic","intel"],vector:"endpoint",clue:"A computer wrote a large archive to removable media outside business hours.",evidence:"Protected data is copied to portable storage attached to an authorised workstation."},
  {id:"cdn",stage:3,title:"Content delivery covert channel",detect:["dns","network","firewall"],vector:"application",clue:"Requests to a content delivery service carry unusually regular, random-looking values.",evidence:"Command data is hidden inside cache and content-delivery requests."},
  {id:"reconsuppress",stage:3,title:"Reconciliation suppression",detect:["server","intel","settlement-recon"],vector:"application",clue:"A reconciliation report balances against a ledger that does not.",evidence:"Reconciliation output was suppressed for selected entries, so the settlement summary reports a balanced position the underlying ledger does not support."},
  {id:"record-export",stage:3,title:"Public record bulk export",detect:["server","intel","firewall"],vector:"application",clue:"A records interface returns far more than a caseworker would ask for.",evidence:"A records interface served bulk responses far beyond a caseworker's pattern, drawing citizen records across case boundaries in a single sweep."},
  {id:"telemetry-out",stage:3,title:"Telemetry channel misuse",detect:["network","server","intel"],vector:"application",clue:"A plant telemetry feed carries more than it reports.",evidence:"A plant telemetry feed carried payloads larger than its own schema allows, using a path the process network is expected to keep open."},
  {id:"backup-out",stage:3,title:"Backup replication diversion",detect:["server","intel","firewall"],vector:"application",clue:"A backup job replicates to a destination nobody registered.",evidence:"A backup job replicated to a destination that appears in no register, moving whole datasets through a route built to carry exactly that."},
  {id:"manifest",stage:3,title:"Manifest and berth-plan manipulation",detect:["server","network","manifest-recon"],vector:"application",clue:"A cargo declaration and the berth plan describe different vessels.",evidence:"Cargo declarations were altered against the berth plan they should match, moving what a container is recorded to hold without moving the container, and the altered declarations were relayed to a party outside the port community."},
  {id:"beneficiary",stage:3,title:"Beneficiary redirection",detect:["intel","identity","firewall","settlement-recon"],vector:"application",clue:"Standing payment instructions change without a corresponding request.",evidence:"Standing beneficiary details were changed without a corresponding customer request, so legitimate instructions settle to an account the customer never nominated."},
];

export type Scenario = {id:string;icon:typeof Building2;sector:string;title:string;summary:string;brief:string;scope:string;timeline:string;constraints:string;impact:string;lesson:string;leads:string[];choices:string[][];preferred:[string,string]};
export const scenarios: Scenario[] = [
  {id:"quiet-office",icon:Building2,sector:"ENTERPRISE IT",title:"The quiet intrusion",summary:"An ordinary morning. An unusual sign-in. A foothold hidden in the noise.",brief:"It is 08:40. Two staff report unusual workstation behaviour, while a routine check shows unexpected outbound traffic. Business applications still operate. Determine how access was gained and what followed.",scope:"Employee endpoints, identity services, remote access, internal application servers and the company's cloud tenancy. Only simulated evidence is used.",timeline:"Reports began this morning. The evidence window covers the preceding 24 hours.",constraints:"Telemetry is incomplete. A failed check settles nothing, and a completed one rules out only what its own source could have seen.",impact:"Payroll and shared business applications remain available, but confidence in privileged identities is falling.",lesson:"Could your team connect an endpoint report, an identity event and outbound traffic without treating them as separate incidents?",leads:["Two weak signals overlap: a user complaint and an outbound-traffic anomaly. Neither identifies the entry point.","Authentication, endpoint and egress timestamps do not align cleanly. Establish which record is causal.","A staff sign-in came from an unfamiliar place at about the time a familiar-looking program started on one workstation."],choices:[["joiner","phish","vpn","token"],["printqueue","spray","dump","trust"],["gpo","task","account","key"],["backup-out","dnsout","saas","beacon"]],preferred:["credential","rebuild"]},
  {id:"care-network",icon:HeartPulse,sector:"HEALTHCARE",title:"After the night shift",summary:"Clinical services remain live while unfamiliar activity spreads behind the scenes.",brief:"At a fictional hospital, overnight staff report a sluggish workstation and unfamiliar remote sessions. Patient-facing services remain available. Investigate without assuming shutdown is the safe first action.",scope:"Administrative endpoints, the support gateway, identity services and clinical application servers. Medical devices are outside this attack chain.",timeline:"The first anomalies occurred during the night shift. Records cover that shift and the previous working day.",constraints:"Clinical continuity matters. Isolation can reduce risk but may interrupt time-sensitive work.",impact:"Patient care is continuing. The greatest immediate risk is loss of access to supporting records and scheduling.",lesson:"Who would authorise isolation of a system supporting clinical work, and what evidence would they need?",leads:["A slow endpoint and unfamiliar remote sessions may share a cause, or may be unrelated operational noise.","Support accounts cross several services during the night shift. Some of that activity is expected.","Overnight, a clinical support queue was switched to manual processing after repeated timeouts."],choices:[["supply","helpdesk","redirect","oauth"],["remote","kerberoast","pivot","db-cred"],["logon","registry","mailbox","webshell"],["https","dns-txt","mailout","physical"]],preferred:["credential","restore"]},
  {id:"power-support",icon:Factory,sector:"ENERGY / OT SUPPORT",title:"Beyond the gateway",summary:"A supplier session raises questions at the boundary of plant support systems.",brief:"A fictional power operator sees an unusual supplier session to its maintenance environment. A support server later makes unfamiliar connections. Generation remains stable. Reconstruct the support-system compromise.",scope:"Supplier remote access, the maintenance jump host, identity services and support servers. Controllers and safety systems are not in scope.",timeline:"The suspicious session started after the approved maintenance window. Review the next twelve hours.",constraints:"Investigation is read-only. Distinguish a support-system breach from a process-safety event.",impact:"Generation is stable, but support access cannot yet be trusted. A rushed shutdown could introduce its own operational risk.",lesson:"Could you revoke supplier access without losing essential operational support, and who owns that decision?",leads:["A supplier session and server traffic are correlated in time, but not yet proven to share an identity.","The support environment has legitimate remote administration that can resemble lateral movement.","Boundary records are strong; host telemetry on the jump server has gaps."],choices:[["vendor","lapsed-vpn","share","removable"],["delegation","scheduled","proxy","pivot"],["timer","wmi-sub","githook","sshkey"],["beacon","deadrop","tunnel","dns-txt"]],preferred:["monitor","rebuild"]},
  {id:"port-terminal",icon:Ship,sector:"MARITIME",title:"A terminal under watch",summary:"A booking portal anomaly arrives during a busy operating window.",brief:"A fictional container terminal reports unusual requests to its booking portal. Support staff then spot unexplained server activity. Vessel operations continue. Establish the attack chain before the terminal's schedule runs out.",scope:"The booking portal, application servers, identity services and business network. Crane control systems are excluded.",timeline:"Portal anomalies began at 05:30, followed by internal activity during the morning shift.",constraints:"Busy operations hide suspicious traffic. Preserve evidence before disruptive changes.",impact:"Bookings continue, but partner data and vessel schedules may be exposed if the portal is not trustworthy.",lesson:"Which partners need early warning if an operational dependency can no longer be trusted?",leads:["A burst of portal requests could be partner traffic, automated abuse or exploitation.","Server activity follows the anomaly, but the available logs cannot yet prove direction of travel.","Partner identities and public application traffic overlap in the same time window."],choices:[["pcs-cred","web","kiosk","phish"],["tos-access","db-cred","keyreuse","spray"],["webshell","resolver-svc","sshkey","service"],["manifest","paste","mailout","beacon"]],preferred:["isolate","restore"]},
  {id:"cloud-control",icon:Cloud,sector:"CLOUD SERVICES",title:"An identity out of place",summary:"An automation account begins acting beyond its normal workload.",brief:"A fictional cloud provider detects unusual control-plane activity and an egress-cost spike. No scheduled deployment explains either. Investigate the identity, permission path and mechanism maintaining access.",scope:"Workload credentials, access management, control-plane logs and object-storage activity. No real cloud account is connected.",timeline:"The anomaly began several hours after the last approved deployment.",constraints:"Successful API calls can still be malicious. Attribute the caller before assuming the credential’s owner acted.",impact:"Customer workloads are online. Unchecked privilege expansion could expose multiple tenants and increase transfer costs.",lesson:"Could you rotate a compromised workload credential safely and identify every role and key derived from it?",leads:["Valid API calls and higher transfer volume are the only confirmed facts.","The credential owner, execution location and assumed role may be three different things.","A role's permissions were widened yesterday, and nobody has yet matched the change to a deployment."],choices:[["token","apikey","mfa","web"],["session","ci","snapshot","proxy"],["grant","federation","svc-key","githook"],["deadrop","splitzip","webhook","saas"]],preferred:["credential","rebuild"]},
  {id:"shared-services",icon:Network,sector:"DIGITAL INFRASTRUCTURE",title:"A trusted connection",summary:"A shared-service identity links an isolated alert to a wider incident.",brief:"A fictional shared-services operator sees an unfamiliar session under a trusted support identity. A dependent application later reports unexpected access. Service remains available, but scope is unclear.",scope:"Remote support, identity services, shared application servers, the shared cloud platform and outbound records. Connected organisations are not directly accessible.",timeline:"Anomalies cluster around the last support window. Begin with the shared service’s own evidence.",constraints:"Do not assume trust extends across every connected service. Separate confirmed evidence from partner reports.",impact:"Dependent organisations still receive service, but each additional minute increases the chance of propagating bad trust decisions.",lesson:"What evidence can you share promptly, and how will you separate confirmed facts from assumptions?",leads:["A trusted identity appears in two environments, but only one side has complete telemetry.","The dependent application report may reveal scope, or may be a separate incident.","An administrator from the shared-services side signed in to a tenant system at an hour nobody normally works."],choices:[["resolver","removable","sideload","mfa"],["mgmt-platform","implant","wmi","role"],["backbone","role-trust","image","task"],["cdn","stream","tunnel","git-out"]],preferred:["credential","patch"]},
  {id:"government-service",icon:Landmark,sector:"GOVERNMENT DIGITAL SERVICE",title:"Authority under pressure",summary:"A privileged administrative identity appears across citizen-service systems.",brief:"A fictional government digital service detects anomalous privileged access shortly before a high-demand public transaction window. Services remain available, but the trust boundary is uncertain.",scope:"Administrative identities, citizen-service applications, shared hosting and outbound telemetry.",timeline:"The first privileged event occurred ninety minutes before the demand surge.",constraints:"Public access must be preserved where safe. Attribution is incomplete and multiple agencies depend on the platform.",impact:"A loss of trust could delay essential public transactions and trigger cross-agency coordination.",lesson:"How quickly can confirmed facts be shared without overstating scope?",leads:["A privileged action is confirmed, but the initiating identity may have been replayed.","Application and identity logs disagree on the apparent source.","A shared administrative path may connect otherwise separate services."],choices:[["id-broker","citizen-portal","web","supply"],["session","role","trust","pivot"],["gov-platform","account","federation","webshell"],["record-export","git-out","storage","mailout"]],preferred:["credential","rebuild"]},
  {id:"telecom-core",icon:RadioTower,sector:"INFOCOMM",title:"Signals in the core",summary:"Management-plane activity overlaps with an emerging service-quality issue.",brief:"A fictional telecommunications provider observes unusual management access while customers report intermittent service degradation. Determine whether the events form one incident.",scope:"Management identities, support systems, network-management servers, the cloud-hosted provisioning platform and egress records. Live customer traffic content is excluded.",timeline:"The access anomaly preceded service reports by forty minutes.",constraints:"Containment must avoid unnecessary loss of national connectivity.",impact:"Service remains broadly available, but further degradation could affect dependent essential services.",lesson:"Which control-plane actions require immediate joint cyber and operations authority?",leads:["A valid support session accessed an uncommon management path.","Service degradation may be operational noise or an attacker consequence.","Several management changes were logged under maintenance tickets nobody remembers raising."],choices:[["vpn-token","token","vendor","supply"],["provisioning","remote","trust","keyreuse"],["routepolicy","service","role-trust","mailbox"],["beacon","ssh-out","cdn","webhook"]],preferred:["monitor","rebuild"]},
  {id:"water-operations",icon:Droplets,sector:"WATER / OT SUPPORT",title:"Pressure boundary",summary:"A support-system anomaly emerges while treatment operations remain stable.",brief:"A fictional water operator identifies an unapproved remote session and configuration access in an engineering support environment. Treatment remains within safe operating limits.",scope:"Remote support, engineering workstations, historian support and identity services. Process controllers remain read-only in this exercise.",timeline:"The session began after a vendor maintenance task was closed.",constraints:"Cyber actions must preserve safe and continuous water operations.",impact:"Operations are stable, but engineering trust and future maintenance confidence are degrading.",lesson:"Can the team distinguish compromise of engineering support from a process-safety event?",leads:["Vendor access remained active beyond its approved window.","A support workstation and historian show related but incomplete evidence.","The historian shows readings requested at hours when no operator was on shift."],choices:[["engineer-vpn","phish","helpdesk","share"],["historian","implant","kerberoast","proxy"],["engstation","resolver-svc","timer","account"],["telemetry-out","spool","physical","tunnel"]],preferred:["credential","restore"]},
  {id:"financial-clearing",icon:BadgeDollarSign,sector:"BANKING & FINANCE",title:"The clearing window",summary:"An identity anomaly appears before a time-sensitive settlement cycle.",brief:"A fictional financial institution detects unusual privileged activity and an unexpected export pattern before settlement processing. Determine the route without disrupting trusted transactions unnecessarily.",scope:"Privileged identities, payment-support applications, cloud workloads and outbound transfer records.",timeline:"Activity began two hours before the next settlement cycle.",constraints:"Integrity and availability matter equally. Decisions must be defensible under tight time pressure.",impact:"Transactions continue, but data integrity and settlement confidence could deteriorate rapidly.",lesson:"What evidence is sufficient to constrain access before a critical financial window?",leads:["A valid privileged identity initiated unusual but permitted activity.","The export pattern may be reconciliation traffic or staged data.","Two reconciliation reports for the same window disagree by a small amount."],choices:[["approver","vpn","apikey","resolver"],["entitlement","vault","session","db-cred"],["paysupport","grant","key","wmi-sub"],["beneficiary","reconsuppress","mailout","splitzip"]],preferred:["credential","rebuild"]},
];

export type Difficulty = "training"|"operational"|"crisis";
export const difficulties: Record<Difficulty,{title:string;description:string;threshold:number;maxTurns:number;startImpact:number}> = {
  training:{title:"Training",description:"More time and a clearer margin to learn in; the score allows six turns before a slower finish costs anything.",threshold:10,maxTurns:12,startImpact:14},
  operational:{title:"Operational",description:"Balanced uncertainty, pressure and time.",threshold:11,maxTurns:11,startImpact:22},
  crisis:{title:"Crisis",description:"Tighter rolls, fewer turns and higher starting impact.",threshold:12,maxTurns:10,startImpact:34},
};

export const hypotheses: {id:HypothesisId;title:string;premise:string;procedures:string[]}[] = [
  {id:"identity",title:"Identity-led intrusion",premise:"A real account, sign-in or granted permission is being misused — to get in, to move around and to take data out.",procedures:["identity","firewall","cloud","hunt","email"]},
  {id:"endpoint",title:"Compromised host",premise:"Malicious software on a computer or server is doing the work, from the first program it runs, even one that arrived in a trusted update, to whatever it sends out.",procedures:["endpoint","forensic","server","hunt"]},
  {id:"application",title:"Application or supplier path",premise:"A public-facing application, a supplier's delivery channel or the open internet is doing the work — an exposed service or a vendor push on the way in, web, hosting or DNS traffic on the way out.",procedures:["server","network","firewall","intel","dns"]},
  {id:"cloud",title:"Cloud control-plane abuse",premise:"Cloud keys, roles and settings are being used beyond what they were set up for — in the cloud account's own management, storage and connected services.",procedures:["cloud","identity","hunt"]},
];

// One investigative action per sector that exists nowhere else. The eleven shared
// procedures are right — responders do use the same evidence sources everywhere —
// but every sector also has a reconciliation only its own people would think to
// run. It is offered alongside the shared set in its own scenario, and it joins
// the source list of the reading that matches its vector — earning the
// own-source bonus when that reading is declared — so it sits inside the
// reasoning system rather than beside it.
export const sectorProcedures: {id:string;title:string;short:string;description:string;question:string;vector:HypothesisId}[] = [
  {id:"change-review",title:"Change and approval review",short:"Privileged change records against what changed",description:"Reconcile the privileged change record with the changes systems actually received.",question:"Was every change that landed also requested and approved?",vector:"identity"},
  {id:"downtime-check",title:"Downtime dependency check",short:"Clinical fallback and access dependencies",description:"Validate that clinical downtime procedures still work and which access paths they depend on.",question:"If this path is cut, can care continue on the fallback?",vector:"identity"},
  {id:"work-order",title:"Work order validation",short:"The maintenance permit against the route used",description:"Check the maintenance work order against the access route the session actually took.",question:"Was this maintenance authorised, and did it arrive the way it should have?",vector:"identity"},
  {id:"manifest-recon",title:"Manifest and berth reconciliation",short:"Cargo declarations against the berth plan",description:"Reconcile cargo declarations, manifests and the berth plan against the moves the terminal recorded.",question:"Do the paperwork and the yard describe the same vessel?",vector:"application"},
  {id:"plane-replay",title:"Control-plane change reconstruction",short:"Role and key changes in sequence",description:"Reconstruct control-plane changes in order, across regions and tenants.",question:"In what order were these roles and keys changed, and by which identity?",vector:"cloud"},
  {id:"propagation",title:"Downstream propagation trace",short:"What reached the customers below",description:"Trace what the shared platform pushed downstream and which customers received it.",question:"How far past our own estate did this reach?",vector:"application"},
  {id:"federation-review",title:"Cross-agency federation review",short:"Sign-ins one department vouches for to another",description:"Review identity assertions crossing agency boundaries and the trust that accepted them.",question:"Which department vouched for this, and on what basis?",vector:"identity"},
  {id:"route-compare",title:"Routing change comparison",short:"Live routing against the approved plan",description:"Compare live routing and management-plane state with the approved network plan.",question:"Does the network match the plan it was supposed to be built to?",vector:"application"},
  {id:"historian-recon",title:"Historian reconciliation",short:"Recorded history against process state",description:"Reconcile historian records against the process state operators observed at the time.",question:"Does the record agree with what the plant was actually doing?",vector:"endpoint"},
  {id:"settlement-recon",title:"Approval and settlement reconstruction",short:"The approval chain behind each instruction",description:"Reconstruct the approval sequence behind settled instructions, including who signed and when.",question:"Who approved this, in what order, and does the ledger agree?",vector:"application"},
];

export const scenarioDynamics = [
  {label:"Business service integrity",objective:"Exploit trusted identities and quietly reach shared business data.",reaction:"The actor rotates to another trusted session after detecting intervention.",escalations:["A privileged session begins accessing an additional business service.","Payroll data is staged on an internal share.","A second administrator account shows anomalous activity."],countermeasure:"Earlier identity revocation would have reduced spread, but risked locking out legitimate administrators."},
  {label:"Clinical service continuity",objective:"Use support access to reach administrative records without triggering a clinical outage.",reaction:"The actor shifts activity into a different support account and reduces its request rate.",escalations:["The scheduling service begins responding slowly.","A clinical support queue moves to manual processing.","Staff report intermittent access to administrative records."],countermeasure:"A segmented support path would have limited movement while preserving most clinical activity."},
  {label:"Trusted maintenance access",objective:"Remain inside the support environment and abuse legitimate maintenance pathways.",reaction:"The actor abandons the observed session and moves toward a dormant supplier trust path.",escalations:["A maintenance job is delayed while access is verified.","The jump host can no longer be treated as a trusted administration point.","Operations invokes an alternate maintenance process."],countermeasure:"Revoking all supplier access earlier would have reduced cyber risk but weakened operational support."},
  {label:"Terminal service flow",objective:"Use the booking environment to obtain partner data and disrupt trusted transactions.",reaction:"The actor changes infrastructure and begins blending with partner-originated traffic.",escalations:["Partner bookings require additional verification.","A vessel schedule update enters a manual review queue.","The terminal activates a continuity process for partner transactions."],countermeasure:"Earlier portal isolation would have constrained access but caused a larger partner-service interruption."},
  {label:"Platform availability",objective:"Expand control-plane privileges and export data through legitimate cloud services.",reaction:"The actor exchanges the observed credential for another role and changes the export path.",escalations:["A second tenant boundary requires urgent review.","Unplanned egress cost continues to rise.","The provider restricts one automation workflow pending validation."],countermeasure:"Broad credential rotation would have reduced attacker options but disrupted dependent automation."},
  {label:"Downstream trust",objective:"Propagate through shared identities before dependent organisations can coordinate.",reaction:"The actor lowers activity on the shared service and tests a downstream trust relationship.",escalations:["A dependent organisation requests urgent indicators.","Another connected service suspends automated trust.","Coordination delays leave one downstream environment without confirmed scope."],countermeasure:"Earlier partner notification could have reduced downstream exposure, while sharing less-certain information."},
  {label:"Public service integrity",objective:"Exploit privileged trust to reach multiple citizen-service applications.",reaction:"The actor shifts into a shared administrative identity and lowers its activity rate.",escalations:["A second public service reports anomalous administration.","Transaction queues begin to grow.","Cross-agency coordination moves to crisis posture."],countermeasure:"Earlier privilege restriction could have reduced spread but delayed legitimate public-service administration."},
  {label:"Connectivity continuity",objective:"Abuse management access while blending with legitimate operational change.",reaction:"The actor rotates to a dormant support path and changes its management endpoint.",escalations:["Service degradation expands to another region.","A dependent operator requests urgent assurance.","Network operations restrict nonessential changes."],countermeasure:"Earlier segmentation of management access could have constrained the actor with less customer disruption."},
  {label:"Treatment continuity",objective:"Preserve access to engineering support while approaching operational dependencies.",reaction:"The actor abandons the observed session and tests an older vendor credential.",escalations:["Engineering support enters manual verification.","A maintenance activity is deferred.","Operations increases monitoring of treatment tolerances."],countermeasure:"Earlier vendor-session revocation would have reduced risk while requiring an alternate maintenance process."},
  {label:"Settlement integrity",objective:"Use privileged and cloud access to alter or export sensitive transaction data.",reaction:"The actor exchanges the observed role for another trusted application path.",escalations:["A reconciliation discrepancy requires review.","Settlement staff activate enhanced verification.","A critical processing window approaches with unresolved scope."],countermeasure:"Earlier credential restriction could have reduced exposure while slowing legitimate settlement preparation."},
];

export function attackVector(id:string):HypothesisId {return attacks.find(attack=>attack.id===id)?.vector ?? "endpoint";}

type Inject = {id:string;title:string;text:string;effect:string;effectLabel:string;reason:string};
export type Turn = {number:number;procedure:string;raw:number;modifier:number;total:number;success:boolean;revealed:string|null;narrative:string;inject:Inject|null;injectReveal:string|null;impactChange:number};
export type DecisionRecord = {stage:string;choice:"preserve"|"disrupt";title:string;effect:string};
export type GameStatus = "playing"|"response"|"won"|"lost"|"exercise";
export type Game = {scenario:number;difficulty:Difficulty;chain:string[];revealed:string[];established:string[];lastUsed:Record<string,number>;turns:Turn[];failures:number;nextModifier:number;injectDeck:number[];status:GameStatus;impact:number;pendingDecision:string|null;decisions:DecisionRecord[];responseChoices:string[];responseScore:number;continuity:number};

export const responseOptions = {
  containment:[
    {id:"isolate",title:"Isolate affected systems",description:"Cuts attacker access quickly, but may interrupt service.",impact:-24,continuity:-14,score:12},
    {id:"credential",title:"Revoke identities and sessions",description:"Constrains identity-led movement with moderate operational disruption.",impact:-17,continuity:-5,score:11},
    {id:"monitor",title:"Monitor while mapping scope",description:"Preserves visibility and continuity, but allows risk to persist.",impact:5,continuity:5,score:9},
  ],
  recovery:[
    {id:"rebuild",title:"Rebuild from trusted baseline",description:"Highest confidence, longest service interruption.",impact:-18,continuity:-13,score:14},
    {id:"restore",title:"Restore validated backups",description:"Faster recovery if backup integrity is sound.",impact:-12,continuity:2,score:11},
    {id:"patch",title:"Patch in place and monitor",description:"Fastest return, with more residual uncertainty.",impact:-6,continuity:8,score:7},
  ],
};

export function randomInt(max:number) {if(typeof crypto!=="undefined"&&crypto.getRandomValues){const limit=Math.floor(0x100000000/max)*max;const value=new Uint32Array(1);do{crypto.getRandomValues(value)}while(value[0]>=limit);return value[0]%max;}return Math.floor(Math.random()*max);}
