import { Building2, HeartPulse, Factory, Ship, Cloud, Network } from "lucide-react";

export const stages = [
  {name:"Initial compromise",short:"Entry",color:"#ff967d"},
  {name:"Pivot & escalate",short:"Movement",color:"#e8c968"},
  {name:"Persistence",short:"Foothold",color:"#b49cf4"},
  {name:"C2 & exfiltration",short:"Outbound",color:"#75b9e7"},
];

export const procedures = [
  {id:"endpoint",title:"Endpoint analysis",short:"Processes, execution and host alerts",description:"Examine endpoint telemetry for unusual processes, parent-child relationships and changes to the host.",question:"Which process ran, under whose identity, and what changed?"},
  {id:"identity",title:"Identity audit",short:"Sign-ins, permissions and account changes",description:"Correlate authentication records, group membership and account changes across the identity platform.",question:"Are these sign-ins and privileges consistent with normal activity?"},
  {id:"network",title:"Network analysis",short:"Traffic patterns and east-west activity",description:"Review network flows and packet metadata to identify unusual destinations or movement between systems.",question:"Which systems communicated, and does that path make sense?"},
  {id:"firewall",title:"Firewall review",short:"Boundary connections and egress",description:"Inspect firewall sessions, blocked traffic and remote-access connection records at the relevant boundaries.",question:"What crossed the boundary, when, and in which direction?"},
  {id:"email",title:"Email investigation",short:"Messages, links and delivery traces",description:"Review message headers, delivery logs and suspicious attachments associated with the reported activity.",question:"Was a message or link used to establish the first foothold?"},
  {id:"server",title:"Server inspection",short:"Services, jobs and application logs",description:"Inspect server application logs, services and configuration changes for unexpected execution or access.",question:"Which server-side change or request explains the incident?"},
  {id:"cloud",title:"Cloud audit",short:"API activity, tokens and cloud roles",description:"Correlate control-plane audit events, workload identity activity and API permissions in the cloud environment.",question:"Which identity called which API, and from where?"},
  {id:"dns",title:"DNS review",short:"Lookups, new domains and beaconing",description:"Examine resolver records for repetitive lookups, unusual domains and encoded query patterns.",question:"Do the domain queries expose a communication channel?"},
  {id:"hunt",title:"Targeted threat hunt",short:"Cross-source hypothesis testing",description:"Test a specific hypothesis across endpoint and network telemetry to identify behaviour missed by alerts.",question:"What observable behaviour would confirm our current hypothesis?"},
  {id:"forensic",title:"Forensic triage",short:"Disk, memory and execution artefacts",description:"Collect and analyse preserved artefacts from a suspected host, including execution traces and configuration changes.",question:"What durable artefacts reconstruct how access was established or retained?"},
  {id:"intel",title:"Intelligence correlation",short:"Known infrastructure and indicators",description:"Compare observed destinations and suspicious artefacts against available threat intelligence, while checking context.",question:"Does known malicious infrastructure help explain our observations?"},
];

export type Attack = {id:string;stage:number;title:string;detect:string[];clue:string;evidence:string};
export const attacks: Attack[] = [
  {id:"phish",stage:0,title:"Phishing attachment",detect:["email","endpoint","forensic"],clue:"A document opened shortly before the first host anomaly.",evidence:"Message traces and process ancestry link a delivered attachment to the first malicious execution."},
  {id:"vpn",stage:0,title:"Stolen remote-access account",detect:["identity","firewall","network"],clue:"A valid remote session falls outside its owner’s normal pattern.",evidence:"Remote-access records show a valid account used from an unfamiliar source without corresponding user activity."},
  {id:"web",stage:0,title:"Exploited public application",detect:["server","firewall","forensic"],clue:"Unusual application requests precede unexpected server execution.",evidence:"Application logs tie malformed requests to server-side execution at the start of the incident."},
  {id:"token",stage:0,title:"Exposed cloud credential",detect:["cloud","identity","hunt"],clue:"An automation identity is active outside its workload boundary.",evidence:"Cloud audit records show a workload credential used from outside the approved execution environment."},
  {id:"supply",stage:0,title:"Compromised software update",detect:["endpoint","network","intel"],clue:"Several hosts changed soon after a trusted package was deployed.",evidence:"Package telemetry and process records connect a signed update path to malicious execution on multiple hosts."},
  {id:"oauth",stage:0,title:"Malicious application consent",detect:["identity","cloud","email"],clue:"A user-approved application has begun reading data it never accessed before.",evidence:"Consent and API logs show a deceptive application receiving delegated access to the user’s data."},
  {id:"spray",stage:1,title:"Internal password spraying",detect:["identity","network","hunt"],clue:"Scattered authentication failures are followed by a few successes.",evidence:"A single internal source tries common passwords across many accounts, then authenticates successfully."},
  {id:"remote",stage:1,title:"Remote service execution",detect:["endpoint","network","server"],clue:"An ordinary workstation is making unusual administrative connections.",evidence:"Host and traffic records show remote administrative sessions creating processes on additional systems."},
  {id:"role",stage:1,title:"Cloud role escalation",detect:["cloud","identity","hunt"],clue:"A workload begins using resources beyond its normal permission boundary.",evidence:"An over-permissive role relationship lets the compromised identity assume an elevated cloud role."},
  {id:"dump",stage:1,title:"Credential theft from memory",detect:["endpoint","forensic","hunt"],clue:"A process accessed authentication-related memory without a normal reason.",evidence:"Process-access records and memory artefacts show credential material extracted for additional access."},
  {id:"session",stage:1,title:"Session token replay",detect:["identity","cloud","network"],clue:"The same user session appears in two incompatible locations.",evidence:"Token and access records show a captured session replayed to reach additional services."},
  {id:"trust",stage:1,title:"Trusted service abuse",detect:["server","cloud","network"],clue:"A permitted service path is reaching systems outside its normal dependency map.",evidence:"Service and network records show a trusted integration being used to cross into another environment."},
  {id:"task",stage:2,title:"Malicious scheduled task",detect:["endpoint","server","forensic"],clue:"The same unsigned process returns at regular intervals after termination.",evidence:"A newly created scheduled task relaunches the attacker’s payload at fixed intervals."},
  {id:"account",stage:2,title:"Hidden privileged account",detect:["identity","server","hunt"],clue:"An unexplained account appears in a privileged group.",evidence:"Account-creation and group-change records establish an unapproved privileged identity controlled by the attacker."},
  {id:"webshell",stage:2,title:"Web-shell foothold",detect:["server","forensic","endpoint"],clue:"A recently modified server file launches unusual child processes.",evidence:"A server-side file accepts remote commands and keeps access available through the application."},
  {id:"key",stage:2,title:"Additional access key",detect:["cloud","identity","hunt"],clue:"A new programmatic credential lacks a corresponding change record.",evidence:"Cloud control-plane records show a second access key created to preserve attacker access."},
  {id:"service",stage:2,title:"Rogue system service",detect:["endpoint","server","forensic"],clue:"A new service starts before users sign in and survives a reboot.",evidence:"Service configuration and execution artefacts reveal a persistent malicious binary."},
  {id:"federation",stage:2,title:"Federated trust backdoor",detect:["cloud","identity","server"],clue:"Authentication trust settings changed outside the maintenance window.",evidence:"Control-plane history shows a rogue federation relationship created to maintain privileged access."},
  {id:"https",stage:3,title:"Encrypted web exfiltration",detect:["network","firewall","intel"],clue:"A system repeatedly uploads data to a rarely used web destination.",evidence:"Egress records and destination correlation identify sustained uploads to attacker-controlled infrastructure."},
  {id:"dnsout",stage:3,title:"DNS covert channel",detect:["dns","network","hunt"],clue:"Resolver telemetry contains long, repetitive subdomains.",evidence:"High-entropy DNS queries carry encoded data to an externally controlled domain."},
  {id:"storage",stage:3,title:"Cloud storage export",detect:["cloud","network","firewall"],clue:"Bulk object reads coincide with an outbound transfer spike.",evidence:"Object-access and transfer records correlate bulk retrieval with export to an unapproved destination."},
  {id:"beacon",stage:3,title:"Periodic command beacon",detect:["network","dns","intel"],clue:"Short outbound connections repeat at unusually consistent intervals.",evidence:"Time-series analysis identifies a periodic command channel to new external infrastructure."},
  {id:"saas",stage:3,title:"SaaS synchronisation abuse",detect:["cloud","identity","network"],clue:"An approved synchronisation client suddenly moves far more data than usual.",evidence:"Application and identity logs show a legitimate integration used to export protected records."},
  {id:"deadrop",stage:3,title:"Public dead-drop channel",detect:["intel","network","firewall"],clue:"Hosts poll a common public service with an uncommon request pattern.",evidence:"Proxy and intelligence records reveal commands hidden in content on a public platform."},
];

export type Scenario = {id:string;icon:typeof Building2;sector:string;title:string;summary:string;brief:string;scope:string;timeline:string;constraints:string;impact:string;lesson:string;leads:string[];choices:string[][];preferred:[string,string]};
export const scenarios: Scenario[] = [
  {id:"quiet-office",icon:Building2,sector:"ENTERPRISE IT",title:"The quiet intrusion",summary:"An ordinary morning. An unusual sign-in. A foothold hidden in the noise.",brief:"It is 08:40. Two staff report unusual workstation behaviour, while a routine check shows unexpected outbound traffic. Business applications still operate. Determine how access was gained and what followed.",scope:"Employee endpoints, identity services, remote access and internal application servers. Only simulated evidence is used.",timeline:"Reports began this morning. The evidence window covers the preceding 24 hours.",constraints:"Telemetry is incomplete. A successful action is not proof that an attack technique is absent.",impact:"Payroll and shared business applications remain available, but confidence in privileged identities is falling.",lesson:"Could your team connect an endpoint report, an identity event and outbound traffic without treating them as separate incidents?",leads:["Two weak signals overlap: a user complaint and an outbound-traffic anomaly. Neither identifies the entry point.","Authentication, endpoint and egress timestamps do not align cleanly. Establish which record is causal.","The attacker may be using a legitimate identity or a legitimate-looking process. Test one explanation at a time."],choices:[["phish","vpn","oauth"],["spray","dump","session"],["task","account","service"],["https","beacon","saas"]],preferred:["credential","rebuild"]},
  {id:"care-network",icon:HeartPulse,sector:"HEALTHCARE",title:"After the night shift",summary:"Clinical services remain live while unfamiliar activity spreads behind the scenes.",brief:"At a fictional hospital, overnight staff report a sluggish workstation and unfamiliar remote sessions. Patient-facing services remain available. Investigate without assuming shutdown is the safe first action.",scope:"Administrative endpoints, the support gateway, identity services and clinical application servers. Medical devices are outside this attack chain.",timeline:"The first anomalies occurred during the night shift. Records cover that shift and the previous working day.",constraints:"Clinical continuity matters. Isolation can reduce risk but may interrupt time-sensitive work.",impact:"Patient care is continuing. The greatest immediate risk is loss of access to supporting records and scheduling.",lesson:"Who would authorise isolation of a system supporting clinical work, and what evidence would they need?",leads:["A slow endpoint and unfamiliar remote sessions may share a cause, or may be unrelated operational noise.","Support accounts cross several services during the night shift. Some of that activity is expected.","The safest investigative path is not automatically the fastest containment path."],choices:[["phish","vpn","supply"],["remote","spray","session"],["task","account","service"],["https","dnsout","saas"]],preferred:["credential","restore"]},
  {id:"power-support",icon:Factory,sector:"ENERGY / OT SUPPORT",title:"Beyond the gateway",summary:"A supplier session raises questions at the boundary of plant support systems.",brief:"A fictional power operator sees an unusual supplier session to its maintenance environment. A support server later makes unfamiliar connections. Generation remains stable. Reconstruct the support-system compromise.",scope:"Supplier remote access, the maintenance jump host, identity services and support servers. Controllers and safety systems are not in scope.",timeline:"The suspicious session started after the approved maintenance window. Review the next twelve hours.",constraints:"Investigation is read-only. Distinguish a support-system breach from a process-safety event.",impact:"Generation is stable, but support access cannot yet be trusted. A rushed shutdown could introduce its own operational risk.",lesson:"Could you revoke supplier access without losing essential operational support, and who owns that decision?",leads:["A supplier session and server traffic are correlated in time, but not yet proven to share an identity.","The support environment has legitimate remote administration that can resemble lateral movement.","Boundary records are strong; host telemetry on the jump server has gaps."],choices:[["vpn","web","supply"],["remote","dump","trust"],["task","webshell","service"],["beacon","https","deadrop"]],preferred:["monitor","rebuild"]},
  {id:"port-terminal",icon:Ship,sector:"MARITIME",title:"A terminal under watch",summary:"A booking portal anomaly arrives during a busy operating window.",brief:"A fictional container terminal reports unusual requests to its booking portal. Support staff then spot unexplained server activity. Vessel operations continue. Establish the attack chain before the window closes.",scope:"The booking portal, application servers, identity services and business network. Crane control systems are excluded.",timeline:"Portal anomalies began at 05:30, followed by internal activity during the morning shift.",constraints:"Busy operations hide suspicious traffic. Preserve evidence before disruptive changes.",impact:"Bookings continue, but partner data and vessel schedules may be exposed if the portal is not trustworthy.",lesson:"Which partners need early warning if an operational dependency can no longer be trusted?",leads:["A burst of portal requests could be partner traffic, automated abuse or exploitation.","Server activity follows the anomaly, but the available logs cannot yet prove direction of travel.","Partner identities and public application traffic overlap in the same time window."],choices:[["web","vpn","oauth"],["remote","spray","trust"],["webshell","account","federation"],["https","dnsout","deadrop"]],preferred:["isolate","restore"]},
  {id:"cloud-control",icon:Cloud,sector:"CLOUD SERVICES",title:"An identity out of place",summary:"An automation account begins acting beyond its normal workload.",brief:"A fictional cloud provider detects unusual control-plane activity and an egress-cost spike. No scheduled deployment explains either. Investigate the identity, permission path and mechanism maintaining access.",scope:"Workload credentials, access management, control-plane logs and object-storage activity. No real cloud account is connected.",timeline:"The anomaly began several hours after the last approved deployment.",constraints:"Successful API calls can still be malicious. Attribute the caller before assuming the credential’s owner acted.",impact:"Customer workloads are online. Unchecked privilege expansion could expose multiple tenants and increase transfer costs.",lesson:"Could you rotate a compromised workload credential safely and identify every role and key derived from it?",leads:["Valid API calls and higher transfer volume are the only confirmed facts.","The credential owner, execution location and assumed role may be three different things.","A permission change can explain movement, persistence or normal deployment activity."],choices:[["token","oauth"],["role","session","trust"],["key","federation"],["storage","https","saas"]],preferred:["credential","rebuild"]},
  {id:"shared-services",icon:Network,sector:"DIGITAL INFRASTRUCTURE",title:"A trusted connection",summary:"A shared-service identity links an isolated alert to a wider incident.",brief:"A fictional shared-services operator sees an unfamiliar session under a trusted support identity. A dependent application later reports unexpected access. Service remains available, but scope is unclear.",scope:"Remote support, identity services, shared application servers and outbound records. Connected organisations are not directly accessible.",timeline:"Anomalies cluster around the last support window. Begin with the shared service’s own evidence.",constraints:"Do not assume trust extends across every connected service. Separate confirmed evidence from partner reports.",impact:"Dependent organisations still receive service, but each additional minute increases the chance of propagating bad trust decisions.",lesson:"What evidence can you share promptly, and how will you separate confirmed facts from assumptions?",leads:["A trusted identity appears in two environments, but only one side has complete telemetry.","The dependent application report may reveal scope, or may be a separate incident.","Trust relationships make legitimate administration and attacker movement look similar."],choices:[["vpn","phish","supply"],["spray","remote","session"],["account","task","federation"],["beacon","dnsout","deadrop"]],preferred:["credential","patch"]},
];

export type Difficulty = "training"|"operational"|"crisis";
export const difficulties: Record<Difficulty,{title:string;description:string;threshold:number;maxTurns:number;startImpact:number}> = {
  training:{title:"Training",description:"More time, clearer margin for experimentation.",threshold:10,maxTurns:11,startImpact:14},
  operational:{title:"Operational",description:"Balanced uncertainty, pressure and time.",threshold:11,maxTurns:10,startImpact:22},
  crisis:{title:"Crisis",description:"Tighter rolls, fewer turns and higher starting impact.",threshold:12,maxTurns:9,startImpact:34},
};

export type HypothesisId = "identity"|"endpoint"|"application"|"cloud";
export const hypotheses: {id:HypothesisId;title:string;premise:string;procedures:string[]}[] = [
  {id:"identity",title:"Identity-led intrusion",premise:"A valid account, session or trust path is being abused.",procedures:["identity","firewall","cloud","hunt"]},
  {id:"endpoint",title:"Compromised host",premise:"Execution on an endpoint or server is driving the incident.",procedures:["endpoint","forensic","server","hunt"]},
  {id:"application",title:"Application or supplier path",premise:"A public service, integration or trusted package is the entry route.",procedures:["server","network","firewall","intel"]},
  {id:"cloud",title:"Cloud control-plane abuse",premise:"Tokens, roles or cloud services are being used outside their intended boundary.",procedures:["cloud","identity","network","hunt"]},
];

export const scenarioDynamics = [
  {label:"Business service integrity",objective:"Exploit trusted identities and quietly reach shared business data.",reaction:"The actor rotates to another trusted session after detecting intervention.",escalations:["A privileged session begins accessing an additional business service.","Payroll data is staged on an internal share.","A second administrator account shows anomalous activity."],countermeasure:"Earlier identity revocation would have reduced spread, but risked locking out legitimate administrators."},
  {label:"Clinical service continuity",objective:"Use support access to reach administrative records without triggering a clinical outage.",reaction:"The actor shifts activity into a different support account and reduces its request rate.",escalations:["The scheduling service begins responding slowly.","A clinical support queue moves to manual processing.","Staff report intermittent access to administrative records."],countermeasure:"A segmented support path would have limited movement while preserving most clinical activity."},
  {label:"Trusted maintenance access",objective:"Remain inside the support environment and abuse legitimate maintenance pathways.",reaction:"The actor abandons the observed session and moves toward a dormant supplier trust path.",escalations:["A maintenance job is delayed while access is verified.","The jump host can no longer be treated as a trusted administration point.","Operations invokes an alternate maintenance process."],countermeasure:"Revoking all supplier access earlier would have reduced cyber risk but weakened operational support."},
  {label:"Terminal service flow",objective:"Use the booking environment to obtain partner data and disrupt trusted transactions.",reaction:"The actor changes infrastructure and begins blending with partner-originated traffic.",escalations:["Partner bookings require additional verification.","A vessel schedule update enters a manual review queue.","The terminal activates a continuity process for partner transactions."],countermeasure:"Earlier portal isolation would have constrained access but caused a larger partner-service interruption."},
  {label:"Tenant trust",objective:"Expand control-plane privileges and export data through legitimate cloud services.",reaction:"The actor exchanges the observed credential for another role and changes the export path.",escalations:["A second tenant boundary requires urgent review.","Unplanned egress cost continues to rise.","The provider restricts one automation workflow pending validation."],countermeasure:"Broad credential rotation would have reduced attacker options but disrupted dependent automation."},
  {label:"Downstream trust",objective:"Propagate through shared identities before dependent organisations can coordinate.",reaction:"The actor lowers activity on the shared service and tests a downstream trust relationship.",escalations:["A dependent organisation requests urgent indicators.","Another connected service suspends automated trust.","Coordination delays leave one downstream environment without confirmed scope."],countermeasure:"Earlier partner notification could have reduced downstream exposure, while sharing less-certain information."},
];

const attackVectors: Record<HypothesisId,string[]> = {
  identity:["vpn","oauth","spray","dump","session","account","federation","saas"],
  endpoint:["phish","supply","remote","task","service","https","beacon"],
  application:["web","supply","trust","webshell","deadrop"],
  cloud:["token","oauth","role","session","key","federation","storage","saas"],
};
export function attackVector(id:string):HypothesisId {return (Object.keys(attackVectors) as HypothesisId[]).find(key=>attackVectors[key].includes(id))??"endpoint";}

type Inject = {id:string;title:string;text:string;effect:string;effectLabel:string;reason:string};
export type Turn = {number:number;procedure:string;raw:number;modifier:number;total:number;success:boolean;revealed:string|null;narrative:string;inject:Inject|null;injectReveal:string|null;impactChange:number};
export type DecisionRecord = {stage:string;choice:"preserve"|"disrupt";title:string;effect:string};
export type GameStatus = "playing"|"response"|"won"|"lost"|"exercise";
export type Game = {scenario:number;difficulty:Difficulty;chain:string[];revealed:string[];established:string[];lastUsed:Record<string,number>;turns:Turn[];failures:number;nextModifier:number;injectDeck:number[];status:GameStatus;impact:number;pendingDecision:string|null;decisions:DecisionRecord[];responseChoices:string[];responseScore:number;continuity:number};

export const responseOptions = {
  containment:[
    {id:"isolate",title:"Isolate affected systems",description:"Cuts attacker access quickly, but may interrupt service.",impact:-24,continuity:-14,score:12},
    {id:"credential",title:"Revoke identities and sessions",description:"Constrains identity-led movement with moderate operational disruption.",impact:-17,continuity:-5,score:11},
    {id:"monitor",title:"Monitor while mapping scope",description:"Preserves visibility and continuity, but allows risk to persist.",impact:5,continuity:5,score:9},
  ],
  recovery:[
    {id:"rebuild",title:"Rebuild from trusted baseline",description:"Highest confidence, longest service interruption.",impact:-18,continuity:-13,score:14},
    {id:"restore",title:"Restore validated backups",description:"Faster recovery if backup integrity is sound.",impact:-12,continuity:2,score:11},
    {id:"patch",title:"Patch in place and monitor",description:"Fastest return, with more residual uncertainty.",impact:-6,continuity:8,score:7},
  ],
};

export function randomInt(max:number) {if(typeof crypto!=="undefined"&&crypto.getRandomValues){const limit=Math.floor(0x100000000/max)*max;const value=new Uint32Array(1);do{crypto.getRandomValues(value)}while(value[0]>=limit);return value[0]%max;}return Math.floor(Math.random()*max);}
