// The cases, the stages of an attack chain and the difficulties: what the
// assignment screen shows, apart from the attacks, procedures and routes the
// engine plays with (./game.ts), so the first load carries only these.
import { Building2, HeartPulse, Factory, Ship, Cloud, Network, Landmark, RadioTower, Droplets, BadgeDollarSign } from "lucide-react";
import { registerContent } from "./i18n/content/registry.ts";

export const stages = [
  {name:"Initial compromise",short:"Entry",color:"#ff967d"},
  {name:"Pivot & escalate",short:"Movement",color:"#e8c968"},
  {name:"Persistence",short:"Foothold",color:"#dab6cd"},
  {name:"C2 & exfiltration",short:"Outbound",color:"#75b9e7"},
];

export type Scenario = {id:string;icon:typeof Building2;sector:string;title:string;summary:string;brief:string;scope:string;timeline:string;constraints:string;impact:string;lesson:string;leads:string[];choices:string[][];preferred:[string,string]};
export const scenarios: Scenario[] = [
  {id:"quiet-office",icon:Building2,sector:"Enterprise IT",title:"The quiet intrusion",summary:"Two staff report odd behaviour on their computers, and a routine check finds traffic leaving that nobody expected.",brief:"It is 08:40. Two staff report unusual workstation behaviour, while a routine check shows unexpected outbound traffic. Business applications still operate. Determine how access was gained and what followed.",scope:"Employee endpoints, identity services, remote access, internal application servers and the company's cloud tenancy. Only simulated evidence is used.",timeline:"Reports began this morning. The evidence window covers the preceding 24 hours.",constraints:"Telemetry is incomplete. A failed check settles nothing, and a completed one rules out only what its own source could have seen.",impact:"Payroll and shared business applications remain available, but confidence in privileged identities is falling.",lesson:"Could your team connect an endpoint report, an identity event and outbound traffic without treating them as separate incidents?",leads:["Two weak signals overlap: a user complaint and an outbound-traffic anomaly. Neither identifies the entry point.","Authentication, endpoint and egress timestamps do not align cleanly. Establish which record is causal.","A staff sign-in came from an unfamiliar place at about the time a familiar-looking program started on one workstation."],choices:[["joiner","phish","vpn","token"],["printqueue","spray","dump","trust"],["gpo","task","account","key"],["backup-out","dnsout","saas","beacon"]],preferred:["credential","rebuild"]},
  {id:"care-network",icon:HeartPulse,sector:"Healthcare",title:"After the night shift",summary:"Clinical services remain live while unfamiliar activity spreads behind the scenes.",brief:"At a fictional hospital, overnight staff report a sluggish workstation and unfamiliar remote sessions. Patient-facing services remain available. Investigate without assuming shutdown is the safe first action.",scope:"Administrative endpoints, the support gateway, identity services and clinical application servers. Medical devices are outside this attack chain.",timeline:"The first anomalies occurred during the night shift. Records cover that shift and the previous working day.",constraints:"Clinical continuity matters. Isolation can reduce risk but may interrupt time-sensitive work.",impact:"Patient care is continuing. The greatest immediate risk is loss of access to supporting records and scheduling.",lesson:"Who would authorise isolation of a system supporting clinical work, and what evidence would they need?",leads:["A slow endpoint and unfamiliar remote sessions may share a cause, or may be unrelated operational noise.","Support accounts cross several services during the night shift. Some of that activity is expected.","Overnight, a clinical support queue was switched to manual processing after repeated timeouts."],choices:[["supply","helpdesk","redirect","oauth"],["remote","kerberoast","pivot","db-cred"],["logon","registry","mailbox","webshell"],["https","dns-txt","mailout","physical"]],preferred:["credential","restore"]},
  {id:"power-support",icon:Factory,sector:"Energy, OT support",title:"Beyond the gateway",summary:"A supplier session raises questions at the boundary of plant support systems.",brief:"A fictional power operator sees an unusual supplier session to its maintenance environment. A support server later makes unfamiliar connections. Generation remains stable. Reconstruct the support-system compromise.",scope:"Supplier remote access, the maintenance jump host, identity services and support servers. Controllers and safety systems are not in scope.",timeline:"The suspicious session started after the approved maintenance window. Review the next twelve hours.",constraints:"Investigation is read-only. Distinguish a support-system breach from a process-safety event.",impact:"Generation is stable, but support access cannot yet be trusted. A rushed shutdown could introduce its own operational risk.",lesson:"Could you revoke supplier access without losing essential operational support, and who owns that decision?",leads:["A supplier session and server traffic are correlated in time, but not yet proven to share an identity.","The support environment has legitimate remote administration that can resemble lateral movement.","Boundary records are strong; host telemetry on the jump server has gaps."],choices:[["vendor","lapsed-vpn","share","removable"],["delegation","scheduled","proxy","pivot"],["timer","wmi-sub","githook","sshkey"],["beacon","deadrop","tunnel","dns-txt"]],preferred:["monitor","rebuild"]},
  {id:"port-terminal",icon:Ship,sector:"Maritime",title:"A terminal under watch",summary:"A booking portal anomaly arrives during a busy operating window.",brief:"A fictional container terminal reports unusual requests to its booking portal. Support staff then spot unexplained server activity. Vessel operations continue. Establish the attack chain before the terminal's schedule runs out.",scope:"The booking portal, application servers, identity services and business network. Crane control systems are excluded.",timeline:"Portal anomalies began at 05:30, followed by internal activity during the morning shift.",constraints:"Busy operations hide suspicious traffic. Preserve evidence before disruptive changes.",impact:"Bookings continue, but partner data and vessel schedules may be exposed if the portal is not trustworthy.",lesson:"Which partners need early warning if an operational dependency can no longer be trusted?",leads:["A burst of portal requests could be partner traffic, automated abuse or exploitation.","Server activity follows the anomaly, but the available logs cannot yet prove direction of travel.","Partner identities and public application traffic overlap in the same time window."],choices:[["pcs-cred","web","kiosk","phish"],["tos-access","db-cred","keyreuse","spray"],["webshell","resolver-svc","sshkey","service"],["manifest","paste","mailout","beacon"]],preferred:["isolate","restore"]},
  {id:"cloud-control",icon:Cloud,sector:"Cloud services",title:"An identity out of place",summary:"An automation account begins acting beyond its normal workload.",brief:"A fictional cloud provider detects unusual control-plane activity and an egress-cost spike. No scheduled deployment explains either. Investigate the identity, permission path and mechanism maintaining access.",scope:"Workload credentials, access management, control-plane logs and object-storage activity. No real cloud account is connected.",timeline:"The anomaly began several hours after the last approved deployment.",constraints:"Successful API calls can still be malicious. Attribute the caller before assuming the credential’s owner acted.",impact:"Customer workloads are online. Unchecked privilege expansion could expose multiple tenants and increase transfer costs.",lesson:"Could you rotate a compromised workload credential safely and identify every role and key derived from it?",leads:["Valid API calls and higher transfer volume are the only confirmed facts.","The credential owner, execution location and assumed role may be three different things.","A role's permissions were widened yesterday, and nobody has yet matched the change to a deployment."],choices:[["token","apikey","mfa","web"],["session","ci","snapshot","proxy"],["grant","federation","svc-key","githook"],["deadrop","splitzip","webhook","saas"]],preferred:["credential","rebuild"]},
  {id:"shared-services",icon:Network,sector:"Digital infrastructure",title:"A trusted connection",summary:"A shared-service identity links an isolated alert to a wider incident.",brief:"A fictional shared-services operator sees an unfamiliar session under a trusted support identity. A dependent application later reports unexpected access. Service remains available, but scope is unclear.",scope:"Remote support, identity services, shared application servers, the shared cloud platform and outbound records. Connected organisations are not directly accessible.",timeline:"Anomalies cluster around the last support window. Begin with the shared service’s own evidence.",constraints:"Do not assume trust extends across every connected service. Separate confirmed evidence from partner reports.",impact:"Dependent organisations still receive service, but each additional minute increases the chance of propagating bad trust decisions.",lesson:"What evidence can you share promptly, and how will you separate confirmed facts from assumptions?",leads:["A trusted identity appears in two environments, but only one side has complete telemetry.","The dependent application report may reveal scope, or may be a separate incident.","An administrator from the shared-services side signed in to a tenant system at an hour nobody normally works."],choices:[["resolver","removable","sideload","mfa"],["mgmt-platform","implant","wmi","role"],["backbone","role-trust","image","task"],["cdn","stream","tunnel","git-out"]],preferred:["credential","patch"]},
  {id:"government-service",icon:Landmark,sector:"Government digital service",title:"Authority under pressure",summary:"A privileged administrative identity appears across citizen-service systems.",brief:"A fictional government digital service detects anomalous privileged access shortly before a high-demand public transaction window. Services remain available, but the trust boundary is uncertain.",scope:"Administrative identities, citizen-service applications, shared hosting and outbound telemetry.",timeline:"The first privileged event occurred ninety minutes before the demand surge.",constraints:"Public access must be preserved where safe. Attribution is incomplete and multiple agencies depend on the platform.",impact:"A loss of trust could delay essential public transactions and trigger cross-agency coordination.",lesson:"How quickly can confirmed facts be shared without overstating scope?",leads:["A privileged action is confirmed, but the initiating identity may have been replayed.","Application and identity logs disagree on the apparent source.","A shared administrative path may connect otherwise separate services."],choices:[["id-broker","citizen-portal","web","supply"],["session","role","trust","pivot"],["gov-platform","account","federation","webshell"],["record-export","git-out","storage","mailout"]],preferred:["credential","rebuild"]},
  {id:"telecom-core",icon:RadioTower,sector:"Infocomm",title:"Signals in the core",summary:"Management-plane activity overlaps with an emerging service-quality issue.",brief:"A fictional telecommunications provider observes unusual management access while customers report intermittent service degradation. Determine whether the events form one incident.",scope:"Management identities, support systems, network-management servers, the cloud-hosted provisioning platform and egress records. Live customer traffic content is excluded.",timeline:"The access anomaly preceded service reports by forty minutes.",constraints:"Containment must avoid unnecessary loss of national connectivity.",impact:"Service remains broadly available, but further degradation could affect dependent essential services.",lesson:"Which control-plane actions require immediate joint cyber and operations authority?",leads:["A valid support session accessed an uncommon management path.","Service degradation may be operational noise or an attacker consequence.","Several management changes were logged under maintenance tickets nobody remembers raising."],choices:[["vpn-token","token","vendor","supply"],["provisioning","remote","trust","keyreuse"],["routepolicy","service","role-trust","mailbox"],["beacon","ssh-out","cdn","webhook"]],preferred:["monitor","rebuild"]},
  {id:"water-operations",icon:Droplets,sector:"Water, OT support",title:"Pressure boundary",summary:"A support-system anomaly emerges while treatment operations remain stable.",brief:"A fictional water operator identifies an unapproved remote session and configuration access in an engineering support environment. Treatment remains within safe operating limits.",scope:"Remote support, engineering workstations, historian support and identity services. Process controllers remain read-only in this exercise.",timeline:"The session began after a vendor maintenance task was closed.",constraints:"Cyber actions must preserve safe and continuous water operations.",impact:"Operations are stable, but engineering trust and future maintenance confidence are degrading.",lesson:"Can the team distinguish compromise of engineering support from a process-safety event?",leads:["Vendor access remained active beyond its approved window.","A support workstation and historian show related but incomplete evidence.","The historian shows readings requested at hours when no operator was on shift."],choices:[["engineer-vpn","phish","helpdesk","share"],["historian","implant","kerberoast","proxy"],["engstation","resolver-svc","timer","account"],["telemetry-out","spool","physical","tunnel"]],preferred:["credential","restore"]},
  {id:"financial-clearing",icon:BadgeDollarSign,sector:"Banking and finance",title:"The clearing window",summary:"An identity anomaly appears before a time-sensitive settlement cycle.",brief:"A fictional financial institution detects unusual privileged activity and an unexpected export pattern before settlement processing. Determine the route without disrupting trusted transactions unnecessarily.",scope:"Privileged identities, payment-support applications, cloud workloads and outbound transfer records.",timeline:"Activity began two hours before the next settlement cycle.",constraints:"Integrity and availability matter equally. Decisions must be defensible under tight time pressure.",impact:"Transactions continue, but data integrity and settlement confidence could deteriorate rapidly.",lesson:"What evidence is sufficient to constrain access before a critical financial window?",leads:["A valid privileged identity initiated unusual but permitted activity.","The export pattern may be reconciliation traffic or staged data.","Two reconciliation reports for the same window disagree by a small amount."],choices:[["approver","vpn","apikey","resolver"],["entitlement","vault","session","db-cred"],["paysupport","grant","key","wmi-sub"],["beneficiary","reconsuppress","mailout","splitzip"]],preferred:["credential","rebuild"]},
];

export type Difficulty = "training"|"operational"|"crisis";
export const difficulties: Record<Difficulty,{title:string;description:string;threshold:number;maxTurns:number;startImpact:number}> = {
  training:{title:"Training",description:"More time and a clearer margin to learn in; the score allows six turns before a slower finish costs anything.",threshold:10,maxTurns:12,startImpact:14},
  operational:{title:"Operational",description:"Balanced uncertainty, pressure and time.",threshold:11,maxTurns:11,startImpact:22},
  crisis:{title:"Crisis",description:"Tighter rolls, fewer turns and higher starting impact.",threshold:12,maxTurns:10,startImpact:34},
};

// The words of these tables are a locale's to replace (lib/i18n/content/).
registerContent({ stages, scenarios, difficulties });
